// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: responses/bubble_collect.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WeevilWorldProtobuf.Responses {

  /// <summary>Holder for reflection information generated from responses/bubble_collect.proto</summary>
  public static partial class BubbleCollectReflection {

    #region Descriptor
    /// <summary>File descriptor for responses/bubble_collect.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BubbleCollectReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5yZXNwb25zZXMvYnViYmxlX2NvbGxlY3QucHJvdG8SCXJlc3BvbnNlcxob",
            "cmVzcG9uc2VzL3N0ZFJlc3BvbnNlLnByb3RvImsKDkJ1YmJsZV9Db2xsZWN0",
            "EiMKA3N0ZBgBIAEoCzIWLnJlc3BvbnNlcy5TdGRSZXNwb25zZRIOCgZJdGVt",
            "SWQYAiABKAMSEgoKSXRlbVR5cGVJZBgDIAEoAxIQCghwb3NpdGlvbhgEIAEo",
            "A0JTWjE1NXBpeGVscy5jb20vd3dzZXJ2ZXIvaW50ZXJuYWwvcHJvdG9idWYv",
            "cmVzcG9uc2VzqgIdV2VldmlsV29ybGRQcm90b2J1Zi5SZXNwb25zZXM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::WeevilWorldProtobuf.Responses.StdResponseReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::WeevilWorldProtobuf.Responses.Bubble_Collect), global::WeevilWorldProtobuf.Responses.Bubble_Collect.Parser, new[]{ "Std", "ItemId", "ItemTypeId", "Position" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Bubble_Collect : pb::IMessage<Bubble_Collect>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Bubble_Collect> _parser = new pb::MessageParser<Bubble_Collect>(() => new Bubble_Collect());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Bubble_Collect> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WeevilWorldProtobuf.Responses.BubbleCollectReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Bubble_Collect() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Bubble_Collect(Bubble_Collect other) : this() {
      _hasBits0 = other._hasBits0;
      std_ = other.std_ != null ? other.std_.Clone() : null;
      itemId_ = other.itemId_;
      itemTypeId_ = other.itemTypeId_;
      position_ = other.position_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Bubble_Collect Clone() {
      return new Bubble_Collect(this);
    }

    /// <summary>Field number for the "std" field.</summary>
    public const int StdFieldNumber = 1;
    private global::WeevilWorldProtobuf.Responses.StdResponse std_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::WeevilWorldProtobuf.Responses.StdResponse Std {
      get { return std_; }
      set {
        std_ = value;
      }
    }

    /// <summary>Field number for the "ItemId" field.</summary>
    public const int ItemIdFieldNumber = 2;
    private readonly static long ItemIdDefaultValue = 0L;

    private long itemId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long ItemId {
      get { if ((_hasBits0 & 1) != 0) { return itemId_; } else { return ItemIdDefaultValue; } }
      set {
        _hasBits0 |= 1;
        itemId_ = value;
      }
    }
    /// <summary>Gets whether the "ItemId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasItemId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "ItemId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearItemId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "ItemTypeId" field.</summary>
    public const int ItemTypeIdFieldNumber = 3;
    private readonly static long ItemTypeIdDefaultValue = 0L;

    private long itemTypeId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long ItemTypeId {
      get { if ((_hasBits0 & 2) != 0) { return itemTypeId_; } else { return ItemTypeIdDefaultValue; } }
      set {
        _hasBits0 |= 2;
        itemTypeId_ = value;
      }
    }
    /// <summary>Gets whether the "ItemTypeId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasItemTypeId {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "ItemTypeId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearItemTypeId() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "position" field.</summary>
    public const int PositionFieldNumber = 4;
    private readonly static long PositionDefaultValue = 0L;

    private long position_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Position {
      get { if ((_hasBits0 & 4) != 0) { return position_; } else { return PositionDefaultValue; } }
      set {
        _hasBits0 |= 4;
        position_ = value;
      }
    }
    /// <summary>Gets whether the "position" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasPosition {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "position" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearPosition() {
      _hasBits0 &= ~4;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Bubble_Collect);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Bubble_Collect other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Std, other.Std)) return false;
      if (ItemId != other.ItemId) return false;
      if (ItemTypeId != other.ItemTypeId) return false;
      if (Position != other.Position) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (std_ != null) hash ^= Std.GetHashCode();
      if (HasItemId) hash ^= ItemId.GetHashCode();
      if (HasItemTypeId) hash ^= ItemTypeId.GetHashCode();
      if (HasPosition) hash ^= Position.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (std_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Std);
      }
      if (HasItemId) {
        output.WriteRawTag(16);
        output.WriteInt64(ItemId);
      }
      if (HasItemTypeId) {
        output.WriteRawTag(24);
        output.WriteInt64(ItemTypeId);
      }
      if (HasPosition) {
        output.WriteRawTag(32);
        output.WriteInt64(Position);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (std_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Std);
      }
      if (HasItemId) {
        output.WriteRawTag(16);
        output.WriteInt64(ItemId);
      }
      if (HasItemTypeId) {
        output.WriteRawTag(24);
        output.WriteInt64(ItemTypeId);
      }
      if (HasPosition) {
        output.WriteRawTag(32);
        output.WriteInt64(Position);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (std_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Std);
      }
      if (HasItemId) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ItemId);
      }
      if (HasItemTypeId) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ItemTypeId);
      }
      if (HasPosition) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Position);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Bubble_Collect other) {
      if (other == null) {
        return;
      }
      if (other.std_ != null) {
        if (std_ == null) {
          Std = new global::WeevilWorldProtobuf.Responses.StdResponse();
        }
        Std.MergeFrom(other.Std);
      }
      if (other.HasItemId) {
        ItemId = other.ItemId;
      }
      if (other.HasItemTypeId) {
        ItemTypeId = other.ItemTypeId;
      }
      if (other.HasPosition) {
        Position = other.Position;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (std_ == null) {
              Std = new global::WeevilWorldProtobuf.Responses.StdResponse();
            }
            input.ReadMessage(Std);
            break;
          }
          case 16: {
            ItemId = input.ReadInt64();
            break;
          }
          case 24: {
            ItemTypeId = input.ReadInt64();
            break;
          }
          case 32: {
            Position = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (std_ == null) {
              Std = new global::WeevilWorldProtobuf.Responses.StdResponse();
            }
            input.ReadMessage(Std);
            break;
          }
          case 16: {
            ItemId = input.ReadInt64();
            break;
          }
          case 24: {
            ItemTypeId = input.ReadInt64();
            break;
          }
          case 32: {
            Position = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
