// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: responses/friend_search.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WeevilWorldProtobuf.Responses {

  /// <summary>Holder for reflection information generated from responses/friend_search.proto</summary>
  public static partial class FriendSearchReflection {

    #region Descriptor
    /// <summary>File descriptor for responses/friend_search.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FriendSearchReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch1yZXNwb25zZXMvZnJpZW5kX3NlYXJjaC5wcm90bxIJcmVzcG9uc2VzGhty",
            "ZXNwb25zZXMvc3RkUmVzcG9uc2UucHJvdG8aFG9iamVjdHMvd2VldmlsLnBy",
            "b3RvIlQKDEZyaWVuZFNlYXJjaBIjCgNzdGQYASABKAsyFi5yZXNwb25zZXMu",
            "U3RkUmVzcG9uc2USHwoGd2VldmlsGAIgASgLMg8ub2JqZWN0cy5XZWV2aWxC",
            "U1oxNTVwaXhlbHMuY29tL3d3c2VydmVyL2ludGVybmFsL3Byb3RvYnVmL3Jl",
            "c3BvbnNlc6oCHVdlZXZpbFdvcmxkUHJvdG9idWYuUmVzcG9uc2Vz"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::WeevilWorldProtobuf.Responses.StdResponseReflection.Descriptor, global::WeevilWorldProtobuf.Objects.WeevilReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::WeevilWorldProtobuf.Responses.FriendSearch), global::WeevilWorldProtobuf.Responses.FriendSearch.Parser, new[]{ "Std", "Weevil" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class FriendSearch : pb::IMessage<FriendSearch>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FriendSearch> _parser = new pb::MessageParser<FriendSearch>(() => new FriendSearch());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<FriendSearch> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WeevilWorldProtobuf.Responses.FriendSearchReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FriendSearch() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FriendSearch(FriendSearch other) : this() {
      std_ = other.std_ != null ? other.std_.Clone() : null;
      weevil_ = other.weevil_ != null ? other.weevil_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FriendSearch Clone() {
      return new FriendSearch(this);
    }

    /// <summary>Field number for the "std" field.</summary>
    public const int StdFieldNumber = 1;
    private global::WeevilWorldProtobuf.Responses.StdResponse std_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::WeevilWorldProtobuf.Responses.StdResponse Std {
      get { return std_; }
      set {
        std_ = value;
      }
    }

    /// <summary>Field number for the "weevil" field.</summary>
    public const int WeevilFieldNumber = 2;
    private global::WeevilWorldProtobuf.Objects.Weevil weevil_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::WeevilWorldProtobuf.Objects.Weevil Weevil {
      get { return weevil_; }
      set {
        weevil_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as FriendSearch);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(FriendSearch other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Std, other.Std)) return false;
      if (!object.Equals(Weevil, other.Weevil)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (std_ != null) hash ^= Std.GetHashCode();
      if (weevil_ != null) hash ^= Weevil.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (std_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Std);
      }
      if (weevil_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Weevil);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (std_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Std);
      }
      if (weevil_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Weevil);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (std_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Std);
      }
      if (weevil_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Weevil);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(FriendSearch other) {
      if (other == null) {
        return;
      }
      if (other.std_ != null) {
        if (std_ == null) {
          Std = new global::WeevilWorldProtobuf.Responses.StdResponse();
        }
        Std.MergeFrom(other.Std);
      }
      if (other.weevil_ != null) {
        if (weevil_ == null) {
          Weevil = new global::WeevilWorldProtobuf.Objects.Weevil();
        }
        Weevil.MergeFrom(other.Weevil);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (std_ == null) {
              Std = new global::WeevilWorldProtobuf.Responses.StdResponse();
            }
            input.ReadMessage(Std);
            break;
          }
          case 18: {
            if (weevil_ == null) {
              Weevil = new global::WeevilWorldProtobuf.Objects.Weevil();
            }
            input.ReadMessage(Weevil);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (std_ == null) {
              Std = new global::WeevilWorldProtobuf.Responses.StdResponse();
            }
            input.ReadMessage(Std);
            break;
          }
          case 18: {
            if (weevil_ == null) {
              Weevil = new global::WeevilWorldProtobuf.Objects.Weevil();
            }
            input.ReadMessage(Weevil);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
