// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: responses/weevil.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WeevilWorldProtobuf.Responses {

  /// <summary>Holder for reflection information generated from responses/weevil.proto</summary>
  public static partial class WeevilReflection {

    #region Descriptor
    /// <summary>File descriptor for responses/weevil.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static WeevilReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZyZXNwb25zZXMvd2VldmlsLnByb3RvEglyZXNwb25zZXMaG3Jlc3BvbnNl",
            "cy9zdGRSZXNwb25zZS5wcm90bxoUb2JqZWN0cy93ZWV2aWwucHJvdG8iQwoP",
            "V2VldmlsQ2hhbmdlRGVmEiMKA3N0ZBgBIAEoCzIWLnJlc3BvbnNlcy5TdGRS",
            "ZXNwb25zZRILCgNkZWYYAiABKAkiNgoPV2VldmlsU2V0T3B0aW9uEiMKA3N0",
            "ZBgBIAEoCzIWLnJlc3BvbnNlcy5TdGRSZXNwb25zZSJVCg1XZWV2aWxHZXRE",
            "YXRhEiMKA3N0ZBgBIAEoCzIWLnJlc3BvbnNlcy5TdGRSZXNwb25zZRIfCgZ3",
            "ZWV2aWwYAiABKAsyDy5vYmplY3RzLldlZXZpbCJNCgtXZWFyQ2xvdGhlcxIm",
            "CgZyZXN1bHQYASABKAsyFi5yZXNwb25zZXMuU3RkUmVzcG9uc2USFgoOYWN0",
            "aXZlX2Nsb3RoZXMYAiADKANCU1oxNTVwaXhlbHMuY29tL3d3c2VydmVyL2lu",
            "dGVybmFsL3Byb3RvYnVmL3Jlc3BvbnNlc6oCHVdlZXZpbFdvcmxkUHJvdG9i",
            "dWYuUmVzcG9uc2Vz"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::WeevilWorldProtobuf.Responses.StdResponseReflection.Descriptor, global::WeevilWorldProtobuf.Objects.WeevilReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::WeevilWorldProtobuf.Responses.WeevilChangeDef), global::WeevilWorldProtobuf.Responses.WeevilChangeDef.Parser, new[]{ "Std", "Def" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::WeevilWorldProtobuf.Responses.WeevilSetOption), global::WeevilWorldProtobuf.Responses.WeevilSetOption.Parser, new[]{ "Std" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::WeevilWorldProtobuf.Responses.WeevilGetData), global::WeevilWorldProtobuf.Responses.WeevilGetData.Parser, new[]{ "Std", "Weevil" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::WeevilWorldProtobuf.Responses.WearClothes), global::WeevilWorldProtobuf.Responses.WearClothes.Parser, new[]{ "Result", "ActiveClothes" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class WeevilChangeDef : pb::IMessage<WeevilChangeDef>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WeevilChangeDef> _parser = new pb::MessageParser<WeevilChangeDef>(() => new WeevilChangeDef());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<WeevilChangeDef> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WeevilWorldProtobuf.Responses.WeevilReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WeevilChangeDef() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WeevilChangeDef(WeevilChangeDef other) : this() {
      std_ = other.std_ != null ? other.std_.Clone() : null;
      def_ = other.def_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WeevilChangeDef Clone() {
      return new WeevilChangeDef(this);
    }

    /// <summary>Field number for the "std" field.</summary>
    public const int StdFieldNumber = 1;
    private global::WeevilWorldProtobuf.Responses.StdResponse std_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::WeevilWorldProtobuf.Responses.StdResponse Std {
      get { return std_; }
      set {
        std_ = value;
      }
    }

    /// <summary>Field number for the "def" field.</summary>
    public const int DefFieldNumber = 2;
    private readonly static string DefDefaultValue = "";

    private string def_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Def {
      get { return def_ ?? DefDefaultValue; }
      set {
        def_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "def" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasDef {
      get { return def_ != null; }
    }
    /// <summary>Clears the value of the "def" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearDef() {
      def_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as WeevilChangeDef);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(WeevilChangeDef other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Std, other.Std)) return false;
      if (Def != other.Def) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (std_ != null) hash ^= Std.GetHashCode();
      if (HasDef) hash ^= Def.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (std_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Std);
      }
      if (HasDef) {
        output.WriteRawTag(18);
        output.WriteString(Def);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (std_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Std);
      }
      if (HasDef) {
        output.WriteRawTag(18);
        output.WriteString(Def);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (std_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Std);
      }
      if (HasDef) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Def);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(WeevilChangeDef other) {
      if (other == null) {
        return;
      }
      if (other.std_ != null) {
        if (std_ == null) {
          Std = new global::WeevilWorldProtobuf.Responses.StdResponse();
        }
        Std.MergeFrom(other.Std);
      }
      if (other.HasDef) {
        Def = other.Def;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (std_ == null) {
              Std = new global::WeevilWorldProtobuf.Responses.StdResponse();
            }
            input.ReadMessage(Std);
            break;
          }
          case 18: {
            Def = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (std_ == null) {
              Std = new global::WeevilWorldProtobuf.Responses.StdResponse();
            }
            input.ReadMessage(Std);
            break;
          }
          case 18: {
            Def = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class WeevilSetOption : pb::IMessage<WeevilSetOption>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WeevilSetOption> _parser = new pb::MessageParser<WeevilSetOption>(() => new WeevilSetOption());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<WeevilSetOption> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WeevilWorldProtobuf.Responses.WeevilReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WeevilSetOption() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WeevilSetOption(WeevilSetOption other) : this() {
      std_ = other.std_ != null ? other.std_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WeevilSetOption Clone() {
      return new WeevilSetOption(this);
    }

    /// <summary>Field number for the "std" field.</summary>
    public const int StdFieldNumber = 1;
    private global::WeevilWorldProtobuf.Responses.StdResponse std_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::WeevilWorldProtobuf.Responses.StdResponse Std {
      get { return std_; }
      set {
        std_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as WeevilSetOption);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(WeevilSetOption other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Std, other.Std)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (std_ != null) hash ^= Std.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (std_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Std);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (std_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Std);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (std_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Std);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(WeevilSetOption other) {
      if (other == null) {
        return;
      }
      if (other.std_ != null) {
        if (std_ == null) {
          Std = new global::WeevilWorldProtobuf.Responses.StdResponse();
        }
        Std.MergeFrom(other.Std);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (std_ == null) {
              Std = new global::WeevilWorldProtobuf.Responses.StdResponse();
            }
            input.ReadMessage(Std);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (std_ == null) {
              Std = new global::WeevilWorldProtobuf.Responses.StdResponse();
            }
            input.ReadMessage(Std);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class WeevilGetData : pb::IMessage<WeevilGetData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WeevilGetData> _parser = new pb::MessageParser<WeevilGetData>(() => new WeevilGetData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<WeevilGetData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WeevilWorldProtobuf.Responses.WeevilReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WeevilGetData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WeevilGetData(WeevilGetData other) : this() {
      std_ = other.std_ != null ? other.std_.Clone() : null;
      weevil_ = other.weevil_ != null ? other.weevil_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WeevilGetData Clone() {
      return new WeevilGetData(this);
    }

    /// <summary>Field number for the "std" field.</summary>
    public const int StdFieldNumber = 1;
    private global::WeevilWorldProtobuf.Responses.StdResponse std_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::WeevilWorldProtobuf.Responses.StdResponse Std {
      get { return std_; }
      set {
        std_ = value;
      }
    }

    /// <summary>Field number for the "weevil" field.</summary>
    public const int WeevilFieldNumber = 2;
    private global::WeevilWorldProtobuf.Objects.Weevil weevil_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::WeevilWorldProtobuf.Objects.Weevil Weevil {
      get { return weevil_; }
      set {
        weevil_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as WeevilGetData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(WeevilGetData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Std, other.Std)) return false;
      if (!object.Equals(Weevil, other.Weevil)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (std_ != null) hash ^= Std.GetHashCode();
      if (weevil_ != null) hash ^= Weevil.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (std_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Std);
      }
      if (weevil_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Weevil);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (std_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Std);
      }
      if (weevil_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Weevil);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (std_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Std);
      }
      if (weevil_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Weevil);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(WeevilGetData other) {
      if (other == null) {
        return;
      }
      if (other.std_ != null) {
        if (std_ == null) {
          Std = new global::WeevilWorldProtobuf.Responses.StdResponse();
        }
        Std.MergeFrom(other.Std);
      }
      if (other.weevil_ != null) {
        if (weevil_ == null) {
          Weevil = new global::WeevilWorldProtobuf.Objects.Weevil();
        }
        Weevil.MergeFrom(other.Weevil);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (std_ == null) {
              Std = new global::WeevilWorldProtobuf.Responses.StdResponse();
            }
            input.ReadMessage(Std);
            break;
          }
          case 18: {
            if (weevil_ == null) {
              Weevil = new global::WeevilWorldProtobuf.Objects.Weevil();
            }
            input.ReadMessage(Weevil);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (std_ == null) {
              Std = new global::WeevilWorldProtobuf.Responses.StdResponse();
            }
            input.ReadMessage(Std);
            break;
          }
          case 18: {
            if (weevil_ == null) {
              Weevil = new global::WeevilWorldProtobuf.Objects.Weevil();
            }
            input.ReadMessage(Weevil);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class WearClothes : pb::IMessage<WearClothes>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WearClothes> _parser = new pb::MessageParser<WearClothes>(() => new WearClothes());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<WearClothes> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WeevilWorldProtobuf.Responses.WeevilReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WearClothes() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WearClothes(WearClothes other) : this() {
      result_ = other.result_ != null ? other.result_.Clone() : null;
      activeClothes_ = other.activeClothes_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WearClothes Clone() {
      return new WearClothes(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private global::WeevilWorldProtobuf.Responses.StdResponse result_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::WeevilWorldProtobuf.Responses.StdResponse Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "active_clothes" field.</summary>
    public const int ActiveClothesFieldNumber = 2;
    private static readonly pb::FieldCodec<long> _repeated_activeClothes_codec
        = pb::FieldCodec.ForInt64(16);
    private readonly pbc::RepeatedField<long> activeClothes_ = new pbc::RepeatedField<long>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<long> ActiveClothes {
      get { return activeClothes_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as WearClothes);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(WearClothes other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Result, other.Result)) return false;
      if(!activeClothes_.Equals(other.activeClothes_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (result_ != null) hash ^= Result.GetHashCode();
      hash ^= activeClothes_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (result_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Result);
      }
      activeClothes_.WriteTo(output, _repeated_activeClothes_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (result_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Result);
      }
      activeClothes_.WriteTo(ref output, _repeated_activeClothes_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (result_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Result);
      }
      size += activeClothes_.CalculateSize(_repeated_activeClothes_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(WearClothes other) {
      if (other == null) {
        return;
      }
      if (other.result_ != null) {
        if (result_ == null) {
          Result = new global::WeevilWorldProtobuf.Responses.StdResponse();
        }
        Result.MergeFrom(other.Result);
      }
      activeClothes_.Add(other.activeClothes_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (result_ == null) {
              Result = new global::WeevilWorldProtobuf.Responses.StdResponse();
            }
            input.ReadMessage(Result);
            break;
          }
          case 18:
          case 16: {
            activeClothes_.AddEntriesFrom(input, _repeated_activeClothes_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (result_ == null) {
              Result = new global::WeevilWorldProtobuf.Responses.StdResponse();
            }
            input.ReadMessage(Result);
            break;
          }
          case 18:
          case 16: {
            activeClothes_.AddEntriesFrom(ref input, _repeated_activeClothes_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
