// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: responses/weevil_of_the_week.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WeevilWorldProtobuf.Responses {

  /// <summary>Holder for reflection information generated from responses/weevil_of_the_week.proto</summary>
  public static partial class WeevilOfTheWeekReflection {

    #region Descriptor
    /// <summary>File descriptor for responses/weevil_of_the_week.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static WeevilOfTheWeekReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiJyZXNwb25zZXMvd2VldmlsX29mX3RoZV93ZWVrLnByb3RvEglyZXNwb25z",
            "ZXMaFG9iamVjdHMvd2VldmlsLnByb3RvGhtyZXNwb25zZXMvc3RkUmVzcG9u",
            "c2UucHJvdG8ipgEKE1dlZXZpbE9mVGhlV2Vla0xpc3QSIwoDc3RkGAEgASgL",
            "MhYucmVzcG9uc2VzLlN0ZFJlc3BvbnNlEh8KBndpbm5lchgCIAEoCzIPLm9i",
            "amVjdHMuV2VldmlsEiIKCXJ1bm5lcnNVcBgDIAMoCzIPLm9iamVjdHMuV2Vl",
            "dmlsEiUKDGFsbW9zdE1hZGVJdBgEIAMoCzIPLm9iamVjdHMuV2VldmlsQlNa",
            "MTU1cGl4ZWxzLmNvbS93d3NlcnZlci9pbnRlcm5hbC9wcm90b2J1Zi9yZXNw",
            "b25zZXOqAh1XZWV2aWxXb3JsZFByb3RvYnVmLlJlc3BvbnNlcw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::WeevilWorldProtobuf.Objects.WeevilReflection.Descriptor, global::WeevilWorldProtobuf.Responses.StdResponseReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::WeevilWorldProtobuf.Responses.WeevilOfTheWeekList), global::WeevilWorldProtobuf.Responses.WeevilOfTheWeekList.Parser, new[]{ "Std", "Winner", "RunnersUp", "AlmostMadeIt" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class WeevilOfTheWeekList : pb::IMessage<WeevilOfTheWeekList>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WeevilOfTheWeekList> _parser = new pb::MessageParser<WeevilOfTheWeekList>(() => new WeevilOfTheWeekList());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<WeevilOfTheWeekList> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WeevilWorldProtobuf.Responses.WeevilOfTheWeekReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WeevilOfTheWeekList() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WeevilOfTheWeekList(WeevilOfTheWeekList other) : this() {
      std_ = other.std_ != null ? other.std_.Clone() : null;
      winner_ = other.winner_ != null ? other.winner_.Clone() : null;
      runnersUp_ = other.runnersUp_.Clone();
      almostMadeIt_ = other.almostMadeIt_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WeevilOfTheWeekList Clone() {
      return new WeevilOfTheWeekList(this);
    }

    /// <summary>Field number for the "std" field.</summary>
    public const int StdFieldNumber = 1;
    private global::WeevilWorldProtobuf.Responses.StdResponse std_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::WeevilWorldProtobuf.Responses.StdResponse Std {
      get { return std_; }
      set {
        std_ = value;
      }
    }

    /// <summary>Field number for the "winner" field.</summary>
    public const int WinnerFieldNumber = 2;
    private global::WeevilWorldProtobuf.Objects.Weevil winner_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::WeevilWorldProtobuf.Objects.Weevil Winner {
      get { return winner_; }
      set {
        winner_ = value;
      }
    }

    /// <summary>Field number for the "runnersUp" field.</summary>
    public const int RunnersUpFieldNumber = 3;
    private static readonly pb::FieldCodec<global::WeevilWorldProtobuf.Objects.Weevil> _repeated_runnersUp_codec
        = pb::FieldCodec.ForMessage(26, global::WeevilWorldProtobuf.Objects.Weevil.Parser);
    private readonly pbc::RepeatedField<global::WeevilWorldProtobuf.Objects.Weevil> runnersUp_ = new pbc::RepeatedField<global::WeevilWorldProtobuf.Objects.Weevil>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::WeevilWorldProtobuf.Objects.Weevil> RunnersUp {
      get { return runnersUp_; }
    }

    /// <summary>Field number for the "almostMadeIt" field.</summary>
    public const int AlmostMadeItFieldNumber = 4;
    private static readonly pb::FieldCodec<global::WeevilWorldProtobuf.Objects.Weevil> _repeated_almostMadeIt_codec
        = pb::FieldCodec.ForMessage(34, global::WeevilWorldProtobuf.Objects.Weevil.Parser);
    private readonly pbc::RepeatedField<global::WeevilWorldProtobuf.Objects.Weevil> almostMadeIt_ = new pbc::RepeatedField<global::WeevilWorldProtobuf.Objects.Weevil>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::WeevilWorldProtobuf.Objects.Weevil> AlmostMadeIt {
      get { return almostMadeIt_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as WeevilOfTheWeekList);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(WeevilOfTheWeekList other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Std, other.Std)) return false;
      if (!object.Equals(Winner, other.Winner)) return false;
      if(!runnersUp_.Equals(other.runnersUp_)) return false;
      if(!almostMadeIt_.Equals(other.almostMadeIt_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (std_ != null) hash ^= Std.GetHashCode();
      if (winner_ != null) hash ^= Winner.GetHashCode();
      hash ^= runnersUp_.GetHashCode();
      hash ^= almostMadeIt_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (std_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Std);
      }
      if (winner_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Winner);
      }
      runnersUp_.WriteTo(output, _repeated_runnersUp_codec);
      almostMadeIt_.WriteTo(output, _repeated_almostMadeIt_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (std_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Std);
      }
      if (winner_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Winner);
      }
      runnersUp_.WriteTo(ref output, _repeated_runnersUp_codec);
      almostMadeIt_.WriteTo(ref output, _repeated_almostMadeIt_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (std_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Std);
      }
      if (winner_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Winner);
      }
      size += runnersUp_.CalculateSize(_repeated_runnersUp_codec);
      size += almostMadeIt_.CalculateSize(_repeated_almostMadeIt_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(WeevilOfTheWeekList other) {
      if (other == null) {
        return;
      }
      if (other.std_ != null) {
        if (std_ == null) {
          Std = new global::WeevilWorldProtobuf.Responses.StdResponse();
        }
        Std.MergeFrom(other.Std);
      }
      if (other.winner_ != null) {
        if (winner_ == null) {
          Winner = new global::WeevilWorldProtobuf.Objects.Weevil();
        }
        Winner.MergeFrom(other.Winner);
      }
      runnersUp_.Add(other.runnersUp_);
      almostMadeIt_.Add(other.almostMadeIt_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (std_ == null) {
              Std = new global::WeevilWorldProtobuf.Responses.StdResponse();
            }
            input.ReadMessage(Std);
            break;
          }
          case 18: {
            if (winner_ == null) {
              Winner = new global::WeevilWorldProtobuf.Objects.Weevil();
            }
            input.ReadMessage(Winner);
            break;
          }
          case 26: {
            runnersUp_.AddEntriesFrom(input, _repeated_runnersUp_codec);
            break;
          }
          case 34: {
            almostMadeIt_.AddEntriesFrom(input, _repeated_almostMadeIt_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (std_ == null) {
              Std = new global::WeevilWorldProtobuf.Responses.StdResponse();
            }
            input.ReadMessage(Std);
            break;
          }
          case 18: {
            if (winner_ == null) {
              Winner = new global::WeevilWorldProtobuf.Objects.Weevil();
            }
            input.ReadMessage(Winner);
            break;
          }
          case 26: {
            runnersUp_.AddEntriesFrom(ref input, _repeated_runnersUp_codec);
            break;
          }
          case 34: {
            almostMadeIt_.AddEntriesFrom(ref input, _repeated_almostMadeIt_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
