// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: requests/cash_machine.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WeevilWorldProtobuf.Requests {

  /// <summary>Holder for reflection information generated from requests/cash_machine.proto</summary>
  public static partial class CashMachineReflection {

    #region Descriptor
    /// <summary>File descriptor for requests/cash_machine.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CashMachineReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChtyZXF1ZXN0cy9jYXNoX21hY2hpbmUucHJvdG8SCHJlcXVlc3RzIi4KFENh",
            "c2hNYWNoaW5lX1dpdGhkcmF3EhYKDmJ1c2luZXNzVHlwZUlEGAEgASgDQlFa",
            "MDU1cGl4ZWxzLmNvbS93d3NlcnZlci9pbnRlcm5hbC9wcm90b2J1Zi9yZXF1",
            "ZXN0c6oCHFdlZXZpbFdvcmxkUHJvdG9idWYuUmVxdWVzdHM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::WeevilWorldProtobuf.Requests.CashMachine_Withdraw), global::WeevilWorldProtobuf.Requests.CashMachine_Withdraw.Parser, new[]{ "BusinessTypeID" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class CashMachine_Withdraw : pb::IMessage<CashMachine_Withdraw>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CashMachine_Withdraw> _parser = new pb::MessageParser<CashMachine_Withdraw>(() => new CashMachine_Withdraw());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CashMachine_Withdraw> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WeevilWorldProtobuf.Requests.CashMachineReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CashMachine_Withdraw() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CashMachine_Withdraw(CashMachine_Withdraw other) : this() {
      _hasBits0 = other._hasBits0;
      businessTypeID_ = other.businessTypeID_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CashMachine_Withdraw Clone() {
      return new CashMachine_Withdraw(this);
    }

    /// <summary>Field number for the "businessTypeID" field.</summary>
    public const int BusinessTypeIDFieldNumber = 1;
    private readonly static long BusinessTypeIDDefaultValue = 0L;

    private long businessTypeID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long BusinessTypeID {
      get { if ((_hasBits0 & 1) != 0) { return businessTypeID_; } else { return BusinessTypeIDDefaultValue; } }
      set {
        _hasBits0 |= 1;
        businessTypeID_ = value;
      }
    }
    /// <summary>Gets whether the "businessTypeID" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasBusinessTypeID {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "businessTypeID" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearBusinessTypeID() {
      _hasBits0 &= ~1;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CashMachine_Withdraw);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CashMachine_Withdraw other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BusinessTypeID != other.BusinessTypeID) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasBusinessTypeID) hash ^= BusinessTypeID.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasBusinessTypeID) {
        output.WriteRawTag(8);
        output.WriteInt64(BusinessTypeID);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasBusinessTypeID) {
        output.WriteRawTag(8);
        output.WriteInt64(BusinessTypeID);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasBusinessTypeID) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(BusinessTypeID);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CashMachine_Withdraw other) {
      if (other == null) {
        return;
      }
      if (other.HasBusinessTypeID) {
        BusinessTypeID = other.BusinessTypeID;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            BusinessTypeID = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            BusinessTypeID = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
