// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: requests/rating_collect_reward.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WeevilWorldProtobuf.Requests {

  /// <summary>Holder for reflection information generated from requests/rating_collect_reward.proto</summary>
  public static partial class RatingCollectRewardReflection {

    #region Descriptor
    /// <summary>File descriptor for requests/rating_collect_reward.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RatingCollectRewardReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiRyZXF1ZXN0cy9yYXRpbmdfY29sbGVjdF9yZXdhcmQucHJvdG8SCHJlcXVl",
            "c3RzIjMKE1JhdGluZ0NvbGxlY3RSZXdhcmQSDgoGYW1vdW50GAEgASgDEgwK",
            "BHNsb3QYAiABKANCUVowNTVwaXhlbHMuY29tL3d3c2VydmVyL2ludGVybmFs",
            "L3Byb3RvYnVmL3JlcXVlc3RzqgIcV2VldmlsV29ybGRQcm90b2J1Zi5SZXF1",
            "ZXN0cw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::WeevilWorldProtobuf.Requests.RatingCollectReward), global::WeevilWorldProtobuf.Requests.RatingCollectReward.Parser, new[]{ "Amount", "Slot" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class RatingCollectReward : pb::IMessage<RatingCollectReward>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RatingCollectReward> _parser = new pb::MessageParser<RatingCollectReward>(() => new RatingCollectReward());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RatingCollectReward> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WeevilWorldProtobuf.Requests.RatingCollectRewardReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RatingCollectReward() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RatingCollectReward(RatingCollectReward other) : this() {
      _hasBits0 = other._hasBits0;
      amount_ = other.amount_;
      slot_ = other.slot_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RatingCollectReward Clone() {
      return new RatingCollectReward(this);
    }

    /// <summary>Field number for the "amount" field.</summary>
    public const int AmountFieldNumber = 1;
    private readonly static long AmountDefaultValue = 0L;

    private long amount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Amount {
      get { if ((_hasBits0 & 1) != 0) { return amount_; } else { return AmountDefaultValue; } }
      set {
        _hasBits0 |= 1;
        amount_ = value;
      }
    }
    /// <summary>Gets whether the "amount" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasAmount {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "amount" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearAmount() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "slot" field.</summary>
    public const int SlotFieldNumber = 2;
    private readonly static long SlotDefaultValue = 0L;

    private long slot_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Slot {
      get { if ((_hasBits0 & 2) != 0) { return slot_; } else { return SlotDefaultValue; } }
      set {
        _hasBits0 |= 2;
        slot_ = value;
      }
    }
    /// <summary>Gets whether the "slot" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasSlot {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "slot" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearSlot() {
      _hasBits0 &= ~2;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RatingCollectReward);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RatingCollectReward other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Amount != other.Amount) return false;
      if (Slot != other.Slot) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasAmount) hash ^= Amount.GetHashCode();
      if (HasSlot) hash ^= Slot.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasAmount) {
        output.WriteRawTag(8);
        output.WriteInt64(Amount);
      }
      if (HasSlot) {
        output.WriteRawTag(16);
        output.WriteInt64(Slot);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasAmount) {
        output.WriteRawTag(8);
        output.WriteInt64(Amount);
      }
      if (HasSlot) {
        output.WriteRawTag(16);
        output.WriteInt64(Slot);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasAmount) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Amount);
      }
      if (HasSlot) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Slot);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RatingCollectReward other) {
      if (other == null) {
        return;
      }
      if (other.HasAmount) {
        Amount = other.Amount;
      }
      if (other.HasSlot) {
        Slot = other.Slot;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Amount = input.ReadInt64();
            break;
          }
          case 16: {
            Slot = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Amount = input.ReadInt64();
            break;
          }
          case 16: {
            Slot = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
