// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enums/emotes.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WeevilWorldProtobuf.Enums {

  /// <summary>Holder for reflection information generated from enums/emotes.proto</summary>
  public static partial class EmotesReflection {

    #region Descriptor
    /// <summary>File descriptor for enums/emotes.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EmotesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJlbnVtcy9lbW90ZXMucHJvdG8SBWVudW1zKiwKCUVtb3RlVHlwZRIOCgpG",
            "aXJzdEVtb3RlEAASDwoLU2Vjb25kRW1vdGUQAUJLWi01NXBpeGVscy5jb20v",
            "d3dzZXJ2ZXIvaW50ZXJuYWwvcHJvdG9idWYvZW51bXOqAhlXZWV2aWxXb3Js",
            "ZFByb3RvYnVmLkVudW1z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::WeevilWorldProtobuf.Enums.EmoteType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum EmoteType {
    [pbr::OriginalName("FirstEmote")] FirstEmote = 0,
    [pbr::OriginalName("SecondEmote")] SecondEmote = 1,
  }

  #endregion

}

#endregion Designer generated code
