// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enums/leaderboard.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WeevilWorldProtobuf.Enums {

  /// <summary>Holder for reflection information generated from enums/leaderboard.proto</summary>
  public static partial class LeaderboardReflection {

    #region Descriptor
    /// <summary>File descriptor for enums/leaderboard.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LeaderboardReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdlbnVtcy9sZWFkZXJib2FyZC5wcm90bxIFZW51bXMqKgoPTGVhZGVyYm9h",
            "cmRUeXBlEgsKB0J1ZGRpZXMQABIKCgZHbG9iYWwQAUJLWi01NXBpeGVscy5j",
            "b20vd3dzZXJ2ZXIvaW50ZXJuYWwvcHJvdG9idWYvZW51bXOqAhlXZWV2aWxX",
            "b3JsZFByb3RvYnVmLkVudW1z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::WeevilWorldProtobuf.Enums.LeaderboardType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum LeaderboardType {
    [pbr::OriginalName("Buddies")] Buddies = 0,
    [pbr::OriginalName("Global")] Global = 1,
  }

  #endregion

}

#endregion Designer generated code
