// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enums/result_type.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WeevilWorldProtobuf.Enums {

  /// <summary>Holder for reflection information generated from enums/result_type.proto</summary>
  public static partial class ResultTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for enums/result_type.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ResultTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdlbnVtcy9yZXN1bHRfdHlwZS5wcm90bxIFZW51bXMqQAoKUmVzdWx0VHlw",
            "ZRIGCgJPSxAAEgYKAktPEAESCQoFRVJST1IQAhIICgRXQUlUEAMSDQoJTk9U",
            "X0ZPVU5EEARCS1otNTVwaXhlbHMuY29tL3d3c2VydmVyL2ludGVybmFsL3By",
            "b3RvYnVmL2VudW1zqgIZV2VldmlsV29ybGRQcm90b2J1Zi5FbnVtcw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::WeevilWorldProtobuf.Enums.ResultType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ResultType {
    [pbr::OriginalName("OK")] Ok = 0,
    [pbr::OriginalName("KO")] Ko = 1,
    [pbr::OriginalName("ERROR")] Error = 2,
    [pbr::OriginalName("WAIT")] Wait = 3,
    [pbr::OriginalName("NOT_FOUND")] NotFound = 4,
  }

  #endregion

}

#endregion Designer generated code
