// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enums/system.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WeevilWorldProtobuf.Enums {

  /// <summary>Holder for reflection information generated from enums/system.proto</summary>
  public static partial class SystemReflection {

    #region Descriptor
    /// <summary>File descriptor for enums/system.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SystemReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJlbnVtcy9zeXN0ZW0ucHJvdG8SBWVudW1zKpcBChJNZW1iZXJzaGlwUGxh",
            "dGZvcm0SEwoPTUVNQkVSU0hJUF9OT05FEAASGgoWTUVNQkVSU0hJUF9CSU5f",
            "V0VFVklMUxABEhIKDk1FTUJFUlNISVBfSU9TEAISFgoSTUVNQkVSU0hJUF9B",
            "TkRST0lEEAMSJAogTUVNQkVSU0hJUF9TVFJJUEVfT05fV0VFVklMV09STEQQ",
            "BEJLWi01NXBpeGVscy5jb20vd3dzZXJ2ZXIvaW50ZXJuYWwvcHJvdG9idWYv",
            "ZW51bXOqAhlXZWV2aWxXb3JsZFByb3RvYnVmLkVudW1z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::WeevilWorldProtobuf.Enums.MembershipPlatform), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum MembershipPlatform {
    [pbr::OriginalName("MEMBERSHIP_NONE")] MembershipNone = 0,
    [pbr::OriginalName("MEMBERSHIP_BIN_WEEVILS")] MembershipBinWeevils = 1,
    [pbr::OriginalName("MEMBERSHIP_IOS")] MembershipIos = 2,
    [pbr::OriginalName("MEMBERSHIP_ANDROID")] MembershipAndroid = 3,
    [pbr::OriginalName("MEMBERSHIP_STRIPE_ON_WEEVILWORLD")] MembershipStripeOnWeevilworld = 4,
  }

  #endregion

}

#endregion Designer generated code
