// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: notifications/nest.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WeevilWorldProtobuf.Notifications {

  /// <summary>Holder for reflection information generated from notifications/nest.proto</summary>
  public static partial class NestReflection {

    #region Descriptor
    /// <summary>File descriptor for notifications/nest.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static NestReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chhub3RpZmljYXRpb25zL25lc3QucHJvdG8SDW5vdGlmaWNhdGlvbnMaF2Vu",
            "dW1zL25lc3Rfc3RhdHVzLnByb3RvIh8KCk5lc3RDbG9zZWQSEQoIT3duZXJJ",
            "ZHgY1hcgASgDIiIKDU5lc3RPd25lckxlZnQSEQoIT3duZXJJZHgY1xcgASgD",
            "IlMKEU5lc3RTdGF0dXNDaGFuZ2VkEhEKCE93bmVySWR4GOoXIAEoAxIrCglO",
            "ZXdTdGF0dXMY6xcgASgOMhEuZW51bXMuTmVzdFN0YXR1czoET3BlbiJcChFM",
            "aWdodFN0YXRlQ2hhbmdlZBILCgNpZHgYASABKAMSDAoEc2xvdBgCIAEoAxIP",
            "CgdsaWdodE9uGAMgASgIEhsKE25leHRMaWdodFRvZ2dsZVVuaXgYBCABKANC",
            "W1o1NTVwaXhlbHMuY29tL3d3c2VydmVyL2ludGVybmFsL3Byb3RvYnVmL25v",
            "dGlmaWNhdGlvbnOqAiFXZWV2aWxXb3JsZFByb3RvYnVmLk5vdGlmaWNhdGlv",
            "bnM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::WeevilWorldProtobuf.Enums.NestStatusReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::WeevilWorldProtobuf.Notifications.NestClosed), global::WeevilWorldProtobuf.Notifications.NestClosed.Parser, new[]{ "OwnerIdx" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::WeevilWorldProtobuf.Notifications.NestOwnerLeft), global::WeevilWorldProtobuf.Notifications.NestOwnerLeft.Parser, new[]{ "OwnerIdx" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::WeevilWorldProtobuf.Notifications.NestStatusChanged), global::WeevilWorldProtobuf.Notifications.NestStatusChanged.Parser, new[]{ "OwnerIdx", "NewStatus" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::WeevilWorldProtobuf.Notifications.LightStateChanged), global::WeevilWorldProtobuf.Notifications.LightStateChanged.Parser, new[]{ "Idx", "Slot", "LightOn", "NextLightToggleUnix" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class NestClosed : pb::IMessage<NestClosed>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<NestClosed> _parser = new pb::MessageParser<NestClosed>(() => new NestClosed());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<NestClosed> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WeevilWorldProtobuf.Notifications.NestReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NestClosed() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NestClosed(NestClosed other) : this() {
      _hasBits0 = other._hasBits0;
      ownerIdx_ = other.ownerIdx_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NestClosed Clone() {
      return new NestClosed(this);
    }

    /// <summary>Field number for the "OwnerIdx" field.</summary>
    public const int OwnerIdxFieldNumber = 3030;
    private readonly static long OwnerIdxDefaultValue = 0L;

    private long ownerIdx_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long OwnerIdx {
      get { if ((_hasBits0 & 1) != 0) { return ownerIdx_; } else { return OwnerIdxDefaultValue; } }
      set {
        _hasBits0 |= 1;
        ownerIdx_ = value;
      }
    }
    /// <summary>Gets whether the "OwnerIdx" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasOwnerIdx {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "OwnerIdx" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearOwnerIdx() {
      _hasBits0 &= ~1;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as NestClosed);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(NestClosed other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (OwnerIdx != other.OwnerIdx) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasOwnerIdx) hash ^= OwnerIdx.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasOwnerIdx) {
        output.WriteRawTag(176, 189, 1);
        output.WriteInt64(OwnerIdx);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasOwnerIdx) {
        output.WriteRawTag(176, 189, 1);
        output.WriteInt64(OwnerIdx);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasOwnerIdx) {
        size += 3 + pb::CodedOutputStream.ComputeInt64Size(OwnerIdx);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(NestClosed other) {
      if (other == null) {
        return;
      }
      if (other.HasOwnerIdx) {
        OwnerIdx = other.OwnerIdx;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 24240: {
            OwnerIdx = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 24240: {
            OwnerIdx = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class NestOwnerLeft : pb::IMessage<NestOwnerLeft>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<NestOwnerLeft> _parser = new pb::MessageParser<NestOwnerLeft>(() => new NestOwnerLeft());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<NestOwnerLeft> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WeevilWorldProtobuf.Notifications.NestReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NestOwnerLeft() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NestOwnerLeft(NestOwnerLeft other) : this() {
      _hasBits0 = other._hasBits0;
      ownerIdx_ = other.ownerIdx_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NestOwnerLeft Clone() {
      return new NestOwnerLeft(this);
    }

    /// <summary>Field number for the "OwnerIdx" field.</summary>
    public const int OwnerIdxFieldNumber = 3031;
    private readonly static long OwnerIdxDefaultValue = 0L;

    private long ownerIdx_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long OwnerIdx {
      get { if ((_hasBits0 & 1) != 0) { return ownerIdx_; } else { return OwnerIdxDefaultValue; } }
      set {
        _hasBits0 |= 1;
        ownerIdx_ = value;
      }
    }
    /// <summary>Gets whether the "OwnerIdx" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasOwnerIdx {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "OwnerIdx" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearOwnerIdx() {
      _hasBits0 &= ~1;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as NestOwnerLeft);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(NestOwnerLeft other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (OwnerIdx != other.OwnerIdx) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasOwnerIdx) hash ^= OwnerIdx.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasOwnerIdx) {
        output.WriteRawTag(184, 189, 1);
        output.WriteInt64(OwnerIdx);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasOwnerIdx) {
        output.WriteRawTag(184, 189, 1);
        output.WriteInt64(OwnerIdx);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasOwnerIdx) {
        size += 3 + pb::CodedOutputStream.ComputeInt64Size(OwnerIdx);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(NestOwnerLeft other) {
      if (other == null) {
        return;
      }
      if (other.HasOwnerIdx) {
        OwnerIdx = other.OwnerIdx;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 24248: {
            OwnerIdx = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 24248: {
            OwnerIdx = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class NestStatusChanged : pb::IMessage<NestStatusChanged>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<NestStatusChanged> _parser = new pb::MessageParser<NestStatusChanged>(() => new NestStatusChanged());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<NestStatusChanged> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WeevilWorldProtobuf.Notifications.NestReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NestStatusChanged() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NestStatusChanged(NestStatusChanged other) : this() {
      _hasBits0 = other._hasBits0;
      ownerIdx_ = other.ownerIdx_;
      newStatus_ = other.newStatus_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NestStatusChanged Clone() {
      return new NestStatusChanged(this);
    }

    /// <summary>Field number for the "OwnerIdx" field.</summary>
    public const int OwnerIdxFieldNumber = 3050;
    private readonly static long OwnerIdxDefaultValue = 0L;

    private long ownerIdx_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long OwnerIdx {
      get { if ((_hasBits0 & 1) != 0) { return ownerIdx_; } else { return OwnerIdxDefaultValue; } }
      set {
        _hasBits0 |= 1;
        ownerIdx_ = value;
      }
    }
    /// <summary>Gets whether the "OwnerIdx" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasOwnerIdx {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "OwnerIdx" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearOwnerIdx() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "NewStatus" field.</summary>
    public const int NewStatusFieldNumber = 3051;
    private readonly static global::WeevilWorldProtobuf.Enums.NestStatus NewStatusDefaultValue = global::WeevilWorldProtobuf.Enums.NestStatus.Open;

    private global::WeevilWorldProtobuf.Enums.NestStatus newStatus_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::WeevilWorldProtobuf.Enums.NestStatus NewStatus {
      get { if ((_hasBits0 & 2) != 0) { return newStatus_; } else { return NewStatusDefaultValue; } }
      set {
        _hasBits0 |= 2;
        newStatus_ = value;
      }
    }
    /// <summary>Gets whether the "NewStatus" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasNewStatus {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "NewStatus" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearNewStatus() {
      _hasBits0 &= ~2;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as NestStatusChanged);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(NestStatusChanged other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (OwnerIdx != other.OwnerIdx) return false;
      if (NewStatus != other.NewStatus) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasOwnerIdx) hash ^= OwnerIdx.GetHashCode();
      if (HasNewStatus) hash ^= NewStatus.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasOwnerIdx) {
        output.WriteRawTag(208, 190, 1);
        output.WriteInt64(OwnerIdx);
      }
      if (HasNewStatus) {
        output.WriteRawTag(216, 190, 1);
        output.WriteEnum((int) NewStatus);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasOwnerIdx) {
        output.WriteRawTag(208, 190, 1);
        output.WriteInt64(OwnerIdx);
      }
      if (HasNewStatus) {
        output.WriteRawTag(216, 190, 1);
        output.WriteEnum((int) NewStatus);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasOwnerIdx) {
        size += 3 + pb::CodedOutputStream.ComputeInt64Size(OwnerIdx);
      }
      if (HasNewStatus) {
        size += 3 + pb::CodedOutputStream.ComputeEnumSize((int) NewStatus);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(NestStatusChanged other) {
      if (other == null) {
        return;
      }
      if (other.HasOwnerIdx) {
        OwnerIdx = other.OwnerIdx;
      }
      if (other.HasNewStatus) {
        NewStatus = other.NewStatus;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 24400: {
            OwnerIdx = input.ReadInt64();
            break;
          }
          case 24408: {
            NewStatus = (global::WeevilWorldProtobuf.Enums.NestStatus) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 24400: {
            OwnerIdx = input.ReadInt64();
            break;
          }
          case 24408: {
            NewStatus = (global::WeevilWorldProtobuf.Enums.NestStatus) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class LightStateChanged : pb::IMessage<LightStateChanged>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LightStateChanged> _parser = new pb::MessageParser<LightStateChanged>(() => new LightStateChanged());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<LightStateChanged> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WeevilWorldProtobuf.Notifications.NestReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LightStateChanged() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LightStateChanged(LightStateChanged other) : this() {
      _hasBits0 = other._hasBits0;
      idx_ = other.idx_;
      slot_ = other.slot_;
      lightOn_ = other.lightOn_;
      nextLightToggleUnix_ = other.nextLightToggleUnix_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LightStateChanged Clone() {
      return new LightStateChanged(this);
    }

    /// <summary>Field number for the "idx" field.</summary>
    public const int IdxFieldNumber = 1;
    private readonly static long IdxDefaultValue = 0L;

    private long idx_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Idx {
      get { if ((_hasBits0 & 1) != 0) { return idx_; } else { return IdxDefaultValue; } }
      set {
        _hasBits0 |= 1;
        idx_ = value;
      }
    }
    /// <summary>Gets whether the "idx" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasIdx {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "idx" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearIdx() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "slot" field.</summary>
    public const int SlotFieldNumber = 2;
    private readonly static long SlotDefaultValue = 0L;

    private long slot_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Slot {
      get { if ((_hasBits0 & 2) != 0) { return slot_; } else { return SlotDefaultValue; } }
      set {
        _hasBits0 |= 2;
        slot_ = value;
      }
    }
    /// <summary>Gets whether the "slot" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasSlot {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "slot" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearSlot() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "lightOn" field.</summary>
    public const int LightOnFieldNumber = 3;
    private readonly static bool LightOnDefaultValue = false;

    private bool lightOn_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool LightOn {
      get { if ((_hasBits0 & 4) != 0) { return lightOn_; } else { return LightOnDefaultValue; } }
      set {
        _hasBits0 |= 4;
        lightOn_ = value;
      }
    }
    /// <summary>Gets whether the "lightOn" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasLightOn {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "lightOn" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearLightOn() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "nextLightToggleUnix" field.</summary>
    public const int NextLightToggleUnixFieldNumber = 4;
    private readonly static long NextLightToggleUnixDefaultValue = 0L;

    private long nextLightToggleUnix_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long NextLightToggleUnix {
      get { if ((_hasBits0 & 8) != 0) { return nextLightToggleUnix_; } else { return NextLightToggleUnixDefaultValue; } }
      set {
        _hasBits0 |= 8;
        nextLightToggleUnix_ = value;
      }
    }
    /// <summary>Gets whether the "nextLightToggleUnix" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasNextLightToggleUnix {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "nextLightToggleUnix" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearNextLightToggleUnix() {
      _hasBits0 &= ~8;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as LightStateChanged);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(LightStateChanged other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Idx != other.Idx) return false;
      if (Slot != other.Slot) return false;
      if (LightOn != other.LightOn) return false;
      if (NextLightToggleUnix != other.NextLightToggleUnix) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasIdx) hash ^= Idx.GetHashCode();
      if (HasSlot) hash ^= Slot.GetHashCode();
      if (HasLightOn) hash ^= LightOn.GetHashCode();
      if (HasNextLightToggleUnix) hash ^= NextLightToggleUnix.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasIdx) {
        output.WriteRawTag(8);
        output.WriteInt64(Idx);
      }
      if (HasSlot) {
        output.WriteRawTag(16);
        output.WriteInt64(Slot);
      }
      if (HasLightOn) {
        output.WriteRawTag(24);
        output.WriteBool(LightOn);
      }
      if (HasNextLightToggleUnix) {
        output.WriteRawTag(32);
        output.WriteInt64(NextLightToggleUnix);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasIdx) {
        output.WriteRawTag(8);
        output.WriteInt64(Idx);
      }
      if (HasSlot) {
        output.WriteRawTag(16);
        output.WriteInt64(Slot);
      }
      if (HasLightOn) {
        output.WriteRawTag(24);
        output.WriteBool(LightOn);
      }
      if (HasNextLightToggleUnix) {
        output.WriteRawTag(32);
        output.WriteInt64(NextLightToggleUnix);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasIdx) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Idx);
      }
      if (HasSlot) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Slot);
      }
      if (HasLightOn) {
        size += 1 + 1;
      }
      if (HasNextLightToggleUnix) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(NextLightToggleUnix);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(LightStateChanged other) {
      if (other == null) {
        return;
      }
      if (other.HasIdx) {
        Idx = other.Idx;
      }
      if (other.HasSlot) {
        Slot = other.Slot;
      }
      if (other.HasLightOn) {
        LightOn = other.LightOn;
      }
      if (other.HasNextLightToggleUnix) {
        NextLightToggleUnix = other.NextLightToggleUnix;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Idx = input.ReadInt64();
            break;
          }
          case 16: {
            Slot = input.ReadInt64();
            break;
          }
          case 24: {
            LightOn = input.ReadBool();
            break;
          }
          case 32: {
            NextLightToggleUnix = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Idx = input.ReadInt64();
            break;
          }
          case 16: {
            Slot = input.ReadInt64();
            break;
          }
          case 24: {
            LightOn = input.ReadBool();
            break;
          }
          case 32: {
            NextLightToggleUnix = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
