// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: notifications/quiz.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WeevilWorldProtobuf.Notifications {

  /// <summary>Holder for reflection information generated from notifications/quiz.proto</summary>
  public static partial class QuizReflection {

    #region Descriptor
    /// <summary>File descriptor for notifications/quiz.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static QuizReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chhub3RpZmljYXRpb25zL3F1aXoucHJvdG8SDW5vdGlmaWNhdGlvbnMaFG9i",
            "amVjdHMvd2VldmlsLnByb3RvGhJvYmplY3RzL3F1aXoucHJvdG8iiwEKCVF1",
            "aXpSb3VuZBIUCgxzdGFydHNBdFVuaXgYASABKAMSEgoKZW5kc0F0VW5peBgC",
            "IAEoAxIgCgdwbGF5ZXJzGAMgAygLMg8ub2JqZWN0cy5XZWV2aWwSMgoLbGVh",
            "ZGVyYm9hcmQYBCADKAsyHS5vYmplY3RzLlF1aXpMZWFkZXJib2FyZEVudHJ5",
            "IjEKDFF1aXpRdWVzdGlvbhIQCghxdWVzdGlvbhgBIAEoCRIPCgdhbnN3ZXJz",
            "GAIgAygJIjMKEFF1aXpQbGF5ZXJKb2luZWQSHwoGd2VldmlsGAEgASgLMg8u",
            "b2JqZWN0cy5XZWV2aWwiHQoOUXVpelBsYXllckxlZnQSCwoDaWR4GAEgASgD",
            "IjgKElF1aXpQbGF5ZXJBbnN3ZXJlZBILCgNpZHgYASABKAMSFQoNY29ycmVj",
            "dEFuc3dlchgCIAEoCCIcCg1RdWl6TmV3TGVhZGVyEgsKA2lkeBgBIAEoA0Jb",
            "WjU1NXBpeGVscy5jb20vd3dzZXJ2ZXIvaW50ZXJuYWwvcHJvdG9idWYvbm90",
            "aWZpY2F0aW9uc6oCIVdlZXZpbFdvcmxkUHJvdG9idWYuTm90aWZpY2F0aW9u",
            "cw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::WeevilWorldProtobuf.Objects.WeevilReflection.Descriptor, global::WeevilWorldProtobuf.Objects.QuizReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::WeevilWorldProtobuf.Notifications.QuizRound), global::WeevilWorldProtobuf.Notifications.QuizRound.Parser, new[]{ "StartsAtUnix", "EndsAtUnix", "Players", "Leaderboard" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::WeevilWorldProtobuf.Notifications.QuizQuestion), global::WeevilWorldProtobuf.Notifications.QuizQuestion.Parser, new[]{ "Question", "Answers" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::WeevilWorldProtobuf.Notifications.QuizPlayerJoined), global::WeevilWorldProtobuf.Notifications.QuizPlayerJoined.Parser, new[]{ "Weevil" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::WeevilWorldProtobuf.Notifications.QuizPlayerLeft), global::WeevilWorldProtobuf.Notifications.QuizPlayerLeft.Parser, new[]{ "Idx" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::WeevilWorldProtobuf.Notifications.QuizPlayerAnswered), global::WeevilWorldProtobuf.Notifications.QuizPlayerAnswered.Parser, new[]{ "Idx", "CorrectAnswer" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::WeevilWorldProtobuf.Notifications.QuizNewLeader), global::WeevilWorldProtobuf.Notifications.QuizNewLeader.Parser, new[]{ "Idx" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class QuizRound : pb::IMessage<QuizRound>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<QuizRound> _parser = new pb::MessageParser<QuizRound>(() => new QuizRound());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<QuizRound> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WeevilWorldProtobuf.Notifications.QuizReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QuizRound() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QuizRound(QuizRound other) : this() {
      _hasBits0 = other._hasBits0;
      startsAtUnix_ = other.startsAtUnix_;
      endsAtUnix_ = other.endsAtUnix_;
      players_ = other.players_.Clone();
      leaderboard_ = other.leaderboard_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QuizRound Clone() {
      return new QuizRound(this);
    }

    /// <summary>Field number for the "startsAtUnix" field.</summary>
    public const int StartsAtUnixFieldNumber = 1;
    private readonly static long StartsAtUnixDefaultValue = 0L;

    private long startsAtUnix_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long StartsAtUnix {
      get { if ((_hasBits0 & 1) != 0) { return startsAtUnix_; } else { return StartsAtUnixDefaultValue; } }
      set {
        _hasBits0 |= 1;
        startsAtUnix_ = value;
      }
    }
    /// <summary>Gets whether the "startsAtUnix" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasStartsAtUnix {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "startsAtUnix" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearStartsAtUnix() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "endsAtUnix" field.</summary>
    public const int EndsAtUnixFieldNumber = 2;
    private readonly static long EndsAtUnixDefaultValue = 0L;

    private long endsAtUnix_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long EndsAtUnix {
      get { if ((_hasBits0 & 2) != 0) { return endsAtUnix_; } else { return EndsAtUnixDefaultValue; } }
      set {
        _hasBits0 |= 2;
        endsAtUnix_ = value;
      }
    }
    /// <summary>Gets whether the "endsAtUnix" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasEndsAtUnix {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "endsAtUnix" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearEndsAtUnix() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "players" field.</summary>
    public const int PlayersFieldNumber = 3;
    private static readonly pb::FieldCodec<global::WeevilWorldProtobuf.Objects.Weevil> _repeated_players_codec
        = pb::FieldCodec.ForMessage(26, global::WeevilWorldProtobuf.Objects.Weevil.Parser);
    private readonly pbc::RepeatedField<global::WeevilWorldProtobuf.Objects.Weevil> players_ = new pbc::RepeatedField<global::WeevilWorldProtobuf.Objects.Weevil>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::WeevilWorldProtobuf.Objects.Weevil> Players {
      get { return players_; }
    }

    /// <summary>Field number for the "leaderboard" field.</summary>
    public const int LeaderboardFieldNumber = 4;
    private static readonly pb::FieldCodec<global::WeevilWorldProtobuf.Objects.QuizLeaderboardEntry> _repeated_leaderboard_codec
        = pb::FieldCodec.ForMessage(34, global::WeevilWorldProtobuf.Objects.QuizLeaderboardEntry.Parser);
    private readonly pbc::RepeatedField<global::WeevilWorldProtobuf.Objects.QuizLeaderboardEntry> leaderboard_ = new pbc::RepeatedField<global::WeevilWorldProtobuf.Objects.QuizLeaderboardEntry>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::WeevilWorldProtobuf.Objects.QuizLeaderboardEntry> Leaderboard {
      get { return leaderboard_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as QuizRound);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(QuizRound other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StartsAtUnix != other.StartsAtUnix) return false;
      if (EndsAtUnix != other.EndsAtUnix) return false;
      if(!players_.Equals(other.players_)) return false;
      if(!leaderboard_.Equals(other.leaderboard_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasStartsAtUnix) hash ^= StartsAtUnix.GetHashCode();
      if (HasEndsAtUnix) hash ^= EndsAtUnix.GetHashCode();
      hash ^= players_.GetHashCode();
      hash ^= leaderboard_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasStartsAtUnix) {
        output.WriteRawTag(8);
        output.WriteInt64(StartsAtUnix);
      }
      if (HasEndsAtUnix) {
        output.WriteRawTag(16);
        output.WriteInt64(EndsAtUnix);
      }
      players_.WriteTo(output, _repeated_players_codec);
      leaderboard_.WriteTo(output, _repeated_leaderboard_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasStartsAtUnix) {
        output.WriteRawTag(8);
        output.WriteInt64(StartsAtUnix);
      }
      if (HasEndsAtUnix) {
        output.WriteRawTag(16);
        output.WriteInt64(EndsAtUnix);
      }
      players_.WriteTo(ref output, _repeated_players_codec);
      leaderboard_.WriteTo(ref output, _repeated_leaderboard_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasStartsAtUnix) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(StartsAtUnix);
      }
      if (HasEndsAtUnix) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(EndsAtUnix);
      }
      size += players_.CalculateSize(_repeated_players_codec);
      size += leaderboard_.CalculateSize(_repeated_leaderboard_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(QuizRound other) {
      if (other == null) {
        return;
      }
      if (other.HasStartsAtUnix) {
        StartsAtUnix = other.StartsAtUnix;
      }
      if (other.HasEndsAtUnix) {
        EndsAtUnix = other.EndsAtUnix;
      }
      players_.Add(other.players_);
      leaderboard_.Add(other.leaderboard_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            StartsAtUnix = input.ReadInt64();
            break;
          }
          case 16: {
            EndsAtUnix = input.ReadInt64();
            break;
          }
          case 26: {
            players_.AddEntriesFrom(input, _repeated_players_codec);
            break;
          }
          case 34: {
            leaderboard_.AddEntriesFrom(input, _repeated_leaderboard_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            StartsAtUnix = input.ReadInt64();
            break;
          }
          case 16: {
            EndsAtUnix = input.ReadInt64();
            break;
          }
          case 26: {
            players_.AddEntriesFrom(ref input, _repeated_players_codec);
            break;
          }
          case 34: {
            leaderboard_.AddEntriesFrom(ref input, _repeated_leaderboard_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class QuizQuestion : pb::IMessage<QuizQuestion>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<QuizQuestion> _parser = new pb::MessageParser<QuizQuestion>(() => new QuizQuestion());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<QuizQuestion> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WeevilWorldProtobuf.Notifications.QuizReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QuizQuestion() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QuizQuestion(QuizQuestion other) : this() {
      question_ = other.question_;
      answers_ = other.answers_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QuizQuestion Clone() {
      return new QuizQuestion(this);
    }

    /// <summary>Field number for the "question" field.</summary>
    public const int QuestionFieldNumber = 1;
    private readonly static string QuestionDefaultValue = "";

    private string question_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Question {
      get { return question_ ?? QuestionDefaultValue; }
      set {
        question_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "question" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasQuestion {
      get { return question_ != null; }
    }
    /// <summary>Clears the value of the "question" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearQuestion() {
      question_ = null;
    }

    /// <summary>Field number for the "answers" field.</summary>
    public const int AnswersFieldNumber = 2;
    private static readonly pb::FieldCodec<string> _repeated_answers_codec
        = pb::FieldCodec.ForString(18);
    private readonly pbc::RepeatedField<string> answers_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> Answers {
      get { return answers_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as QuizQuestion);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(QuizQuestion other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Question != other.Question) return false;
      if(!answers_.Equals(other.answers_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasQuestion) hash ^= Question.GetHashCode();
      hash ^= answers_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasQuestion) {
        output.WriteRawTag(10);
        output.WriteString(Question);
      }
      answers_.WriteTo(output, _repeated_answers_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasQuestion) {
        output.WriteRawTag(10);
        output.WriteString(Question);
      }
      answers_.WriteTo(ref output, _repeated_answers_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasQuestion) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Question);
      }
      size += answers_.CalculateSize(_repeated_answers_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(QuizQuestion other) {
      if (other == null) {
        return;
      }
      if (other.HasQuestion) {
        Question = other.Question;
      }
      answers_.Add(other.answers_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Question = input.ReadString();
            break;
          }
          case 18: {
            answers_.AddEntriesFrom(input, _repeated_answers_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Question = input.ReadString();
            break;
          }
          case 18: {
            answers_.AddEntriesFrom(ref input, _repeated_answers_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class QuizPlayerJoined : pb::IMessage<QuizPlayerJoined>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<QuizPlayerJoined> _parser = new pb::MessageParser<QuizPlayerJoined>(() => new QuizPlayerJoined());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<QuizPlayerJoined> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WeevilWorldProtobuf.Notifications.QuizReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QuizPlayerJoined() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QuizPlayerJoined(QuizPlayerJoined other) : this() {
      weevil_ = other.weevil_ != null ? other.weevil_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QuizPlayerJoined Clone() {
      return new QuizPlayerJoined(this);
    }

    /// <summary>Field number for the "weevil" field.</summary>
    public const int WeevilFieldNumber = 1;
    private global::WeevilWorldProtobuf.Objects.Weevil weevil_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::WeevilWorldProtobuf.Objects.Weevil Weevil {
      get { return weevil_; }
      set {
        weevil_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as QuizPlayerJoined);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(QuizPlayerJoined other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Weevil, other.Weevil)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (weevil_ != null) hash ^= Weevil.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (weevil_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Weevil);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (weevil_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Weevil);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (weevil_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Weevil);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(QuizPlayerJoined other) {
      if (other == null) {
        return;
      }
      if (other.weevil_ != null) {
        if (weevil_ == null) {
          Weevil = new global::WeevilWorldProtobuf.Objects.Weevil();
        }
        Weevil.MergeFrom(other.Weevil);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (weevil_ == null) {
              Weevil = new global::WeevilWorldProtobuf.Objects.Weevil();
            }
            input.ReadMessage(Weevil);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (weevil_ == null) {
              Weevil = new global::WeevilWorldProtobuf.Objects.Weevil();
            }
            input.ReadMessage(Weevil);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class QuizPlayerLeft : pb::IMessage<QuizPlayerLeft>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<QuizPlayerLeft> _parser = new pb::MessageParser<QuizPlayerLeft>(() => new QuizPlayerLeft());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<QuizPlayerLeft> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WeevilWorldProtobuf.Notifications.QuizReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QuizPlayerLeft() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QuizPlayerLeft(QuizPlayerLeft other) : this() {
      _hasBits0 = other._hasBits0;
      idx_ = other.idx_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QuizPlayerLeft Clone() {
      return new QuizPlayerLeft(this);
    }

    /// <summary>Field number for the "idx" field.</summary>
    public const int IdxFieldNumber = 1;
    private readonly static long IdxDefaultValue = 0L;

    private long idx_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Idx {
      get { if ((_hasBits0 & 1) != 0) { return idx_; } else { return IdxDefaultValue; } }
      set {
        _hasBits0 |= 1;
        idx_ = value;
      }
    }
    /// <summary>Gets whether the "idx" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasIdx {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "idx" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearIdx() {
      _hasBits0 &= ~1;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as QuizPlayerLeft);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(QuizPlayerLeft other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Idx != other.Idx) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasIdx) hash ^= Idx.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasIdx) {
        output.WriteRawTag(8);
        output.WriteInt64(Idx);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasIdx) {
        output.WriteRawTag(8);
        output.WriteInt64(Idx);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasIdx) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Idx);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(QuizPlayerLeft other) {
      if (other == null) {
        return;
      }
      if (other.HasIdx) {
        Idx = other.Idx;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Idx = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Idx = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class QuizPlayerAnswered : pb::IMessage<QuizPlayerAnswered>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<QuizPlayerAnswered> _parser = new pb::MessageParser<QuizPlayerAnswered>(() => new QuizPlayerAnswered());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<QuizPlayerAnswered> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WeevilWorldProtobuf.Notifications.QuizReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QuizPlayerAnswered() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QuizPlayerAnswered(QuizPlayerAnswered other) : this() {
      _hasBits0 = other._hasBits0;
      idx_ = other.idx_;
      correctAnswer_ = other.correctAnswer_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QuizPlayerAnswered Clone() {
      return new QuizPlayerAnswered(this);
    }

    /// <summary>Field number for the "idx" field.</summary>
    public const int IdxFieldNumber = 1;
    private readonly static long IdxDefaultValue = 0L;

    private long idx_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Idx {
      get { if ((_hasBits0 & 1) != 0) { return idx_; } else { return IdxDefaultValue; } }
      set {
        _hasBits0 |= 1;
        idx_ = value;
      }
    }
    /// <summary>Gets whether the "idx" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasIdx {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "idx" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearIdx() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "correctAnswer" field.</summary>
    public const int CorrectAnswerFieldNumber = 2;
    private readonly static bool CorrectAnswerDefaultValue = false;

    private bool correctAnswer_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool CorrectAnswer {
      get { if ((_hasBits0 & 2) != 0) { return correctAnswer_; } else { return CorrectAnswerDefaultValue; } }
      set {
        _hasBits0 |= 2;
        correctAnswer_ = value;
      }
    }
    /// <summary>Gets whether the "correctAnswer" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasCorrectAnswer {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "correctAnswer" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearCorrectAnswer() {
      _hasBits0 &= ~2;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as QuizPlayerAnswered);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(QuizPlayerAnswered other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Idx != other.Idx) return false;
      if (CorrectAnswer != other.CorrectAnswer) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasIdx) hash ^= Idx.GetHashCode();
      if (HasCorrectAnswer) hash ^= CorrectAnswer.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasIdx) {
        output.WriteRawTag(8);
        output.WriteInt64(Idx);
      }
      if (HasCorrectAnswer) {
        output.WriteRawTag(16);
        output.WriteBool(CorrectAnswer);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasIdx) {
        output.WriteRawTag(8);
        output.WriteInt64(Idx);
      }
      if (HasCorrectAnswer) {
        output.WriteRawTag(16);
        output.WriteBool(CorrectAnswer);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasIdx) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Idx);
      }
      if (HasCorrectAnswer) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(QuizPlayerAnswered other) {
      if (other == null) {
        return;
      }
      if (other.HasIdx) {
        Idx = other.Idx;
      }
      if (other.HasCorrectAnswer) {
        CorrectAnswer = other.CorrectAnswer;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Idx = input.ReadInt64();
            break;
          }
          case 16: {
            CorrectAnswer = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Idx = input.ReadInt64();
            break;
          }
          case 16: {
            CorrectAnswer = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class QuizNewLeader : pb::IMessage<QuizNewLeader>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<QuizNewLeader> _parser = new pb::MessageParser<QuizNewLeader>(() => new QuizNewLeader());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<QuizNewLeader> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WeevilWorldProtobuf.Notifications.QuizReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QuizNewLeader() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QuizNewLeader(QuizNewLeader other) : this() {
      _hasBits0 = other._hasBits0;
      idx_ = other.idx_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QuizNewLeader Clone() {
      return new QuizNewLeader(this);
    }

    /// <summary>Field number for the "idx" field.</summary>
    public const int IdxFieldNumber = 1;
    private readonly static long IdxDefaultValue = 0L;

    private long idx_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Idx {
      get { if ((_hasBits0 & 1) != 0) { return idx_; } else { return IdxDefaultValue; } }
      set {
        _hasBits0 |= 1;
        idx_ = value;
      }
    }
    /// <summary>Gets whether the "idx" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasIdx {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "idx" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearIdx() {
      _hasBits0 &= ~1;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as QuizNewLeader);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(QuizNewLeader other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Idx != other.Idx) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasIdx) hash ^= Idx.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasIdx) {
        output.WriteRawTag(8);
        output.WriteInt64(Idx);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasIdx) {
        output.WriteRawTag(8);
        output.WriteInt64(Idx);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasIdx) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Idx);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(QuizNewLeader other) {
      if (other == null) {
        return;
      }
      if (other.HasIdx) {
        Idx = other.Idx;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Idx = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Idx = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
