// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: notifications/system.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WeevilWorldProtobuf.Notifications {

  /// <summary>Holder for reflection information generated from notifications/system.proto</summary>
  public static partial class SystemReflection {

    #region Descriptor
    /// <summary>File descriptor for notifications/system.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SystemReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chpub3RpZmljYXRpb25zL3N5c3RlbS5wcm90bxINbm90aWZpY2F0aW9ucyJp",
            "CgtTZXJ2ZXJFcnJvchITCgtkZXNjcmlwdGlvbhgBIAEoCRI8ChNtZXNzYWdl",
            "VG9vTG9uZ0Vycm9yGAIgASgLMh0ubm90aWZpY2F0aW9ucy5NZXNzYWdlVG9v",
            "TG9uZ0gAQgcKBWVycm9yIi0KDk1lc3NhZ2VUb29Mb25nEhsKE29yaWdpbmFs",
            "TWVzc2FnZVR5cGUYASABKA1CW1o1NTVwaXhlbHMuY29tL3d3c2VydmVyL2lu",
            "dGVybmFsL3Byb3RvYnVmL25vdGlmaWNhdGlvbnOqAiFXZWV2aWxXb3JsZFBy",
            "b3RvYnVmLk5vdGlmaWNhdGlvbnM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::WeevilWorldProtobuf.Notifications.ServerError), global::WeevilWorldProtobuf.Notifications.ServerError.Parser, new[]{ "Description", "MessageTooLongError" }, new[]{ "Error" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::WeevilWorldProtobuf.Notifications.MessageTooLong), global::WeevilWorldProtobuf.Notifications.MessageTooLong.Parser, new[]{ "OriginalMessageType" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ServerError : pb::IMessage<ServerError>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ServerError> _parser = new pb::MessageParser<ServerError>(() => new ServerError());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ServerError> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WeevilWorldProtobuf.Notifications.SystemReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ServerError() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ServerError(ServerError other) : this() {
      description_ = other.description_;
      switch (other.ErrorCase) {
        case ErrorOneofCase.MessageTooLongError:
          MessageTooLongError = other.MessageTooLongError.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ServerError Clone() {
      return new ServerError(this);
    }

    /// <summary>Field number for the "description" field.</summary>
    public const int DescriptionFieldNumber = 1;
    private readonly static string DescriptionDefaultValue = "";

    private string description_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Description {
      get { return description_ ?? DescriptionDefaultValue; }
      set {
        description_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "description" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasDescription {
      get { return description_ != null; }
    }
    /// <summary>Clears the value of the "description" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearDescription() {
      description_ = null;
    }

    /// <summary>Field number for the "messageTooLongError" field.</summary>
    public const int MessageTooLongErrorFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::WeevilWorldProtobuf.Notifications.MessageTooLong MessageTooLongError {
      get { return errorCase_ == ErrorOneofCase.MessageTooLongError ? (global::WeevilWorldProtobuf.Notifications.MessageTooLong) error_ : null; }
      set {
        error_ = value;
        errorCase_ = value == null ? ErrorOneofCase.None : ErrorOneofCase.MessageTooLongError;
      }
    }

    private object error_;
    /// <summary>Enum of possible cases for the "error" oneof.</summary>
    public enum ErrorOneofCase {
      None = 0,
      MessageTooLongError = 2,
    }
    private ErrorOneofCase errorCase_ = ErrorOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ErrorOneofCase ErrorCase {
      get { return errorCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearError() {
      errorCase_ = ErrorOneofCase.None;
      error_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ServerError);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ServerError other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Description != other.Description) return false;
      if (!object.Equals(MessageTooLongError, other.MessageTooLongError)) return false;
      if (ErrorCase != other.ErrorCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasDescription) hash ^= Description.GetHashCode();
      if (errorCase_ == ErrorOneofCase.MessageTooLongError) hash ^= MessageTooLongError.GetHashCode();
      hash ^= (int) errorCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasDescription) {
        output.WriteRawTag(10);
        output.WriteString(Description);
      }
      if (errorCase_ == ErrorOneofCase.MessageTooLongError) {
        output.WriteRawTag(18);
        output.WriteMessage(MessageTooLongError);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasDescription) {
        output.WriteRawTag(10);
        output.WriteString(Description);
      }
      if (errorCase_ == ErrorOneofCase.MessageTooLongError) {
        output.WriteRawTag(18);
        output.WriteMessage(MessageTooLongError);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasDescription) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Description);
      }
      if (errorCase_ == ErrorOneofCase.MessageTooLongError) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MessageTooLongError);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ServerError other) {
      if (other == null) {
        return;
      }
      if (other.HasDescription) {
        Description = other.Description;
      }
      switch (other.ErrorCase) {
        case ErrorOneofCase.MessageTooLongError:
          if (MessageTooLongError == null) {
            MessageTooLongError = new global::WeevilWorldProtobuf.Notifications.MessageTooLong();
          }
          MessageTooLongError.MergeFrom(other.MessageTooLongError);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Description = input.ReadString();
            break;
          }
          case 18: {
            global::WeevilWorldProtobuf.Notifications.MessageTooLong subBuilder = new global::WeevilWorldProtobuf.Notifications.MessageTooLong();
            if (errorCase_ == ErrorOneofCase.MessageTooLongError) {
              subBuilder.MergeFrom(MessageTooLongError);
            }
            input.ReadMessage(subBuilder);
            MessageTooLongError = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Description = input.ReadString();
            break;
          }
          case 18: {
            global::WeevilWorldProtobuf.Notifications.MessageTooLong subBuilder = new global::WeevilWorldProtobuf.Notifications.MessageTooLong();
            if (errorCase_ == ErrorOneofCase.MessageTooLongError) {
              subBuilder.MergeFrom(MessageTooLongError);
            }
            input.ReadMessage(subBuilder);
            MessageTooLongError = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class MessageTooLong : pb::IMessage<MessageTooLong>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MessageTooLong> _parser = new pb::MessageParser<MessageTooLong>(() => new MessageTooLong());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MessageTooLong> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WeevilWorldProtobuf.Notifications.SystemReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MessageTooLong() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MessageTooLong(MessageTooLong other) : this() {
      _hasBits0 = other._hasBits0;
      originalMessageType_ = other.originalMessageType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MessageTooLong Clone() {
      return new MessageTooLong(this);
    }

    /// <summary>Field number for the "originalMessageType" field.</summary>
    public const int OriginalMessageTypeFieldNumber = 1;
    private readonly static uint OriginalMessageTypeDefaultValue = 0;

    private uint originalMessageType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint OriginalMessageType {
      get { if ((_hasBits0 & 1) != 0) { return originalMessageType_; } else { return OriginalMessageTypeDefaultValue; } }
      set {
        _hasBits0 |= 1;
        originalMessageType_ = value;
      }
    }
    /// <summary>Gets whether the "originalMessageType" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasOriginalMessageType {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "originalMessageType" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearOriginalMessageType() {
      _hasBits0 &= ~1;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MessageTooLong);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MessageTooLong other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (OriginalMessageType != other.OriginalMessageType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasOriginalMessageType) hash ^= OriginalMessageType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasOriginalMessageType) {
        output.WriteRawTag(8);
        output.WriteUInt32(OriginalMessageType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasOriginalMessageType) {
        output.WriteRawTag(8);
        output.WriteUInt32(OriginalMessageType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasOriginalMessageType) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(OriginalMessageType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MessageTooLong other) {
      if (other == null) {
        return;
      }
      if (other.HasOriginalMessageType) {
        OriginalMessageType = other.OriginalMessageType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            OriginalMessageType = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            OriginalMessageType = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
