// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: objects/collection.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WeevilWorldProtobuf.Objects {

  /// <summary>Holder for reflection information generated from objects/collection.proto</summary>
  public static partial class CollectionReflection {

    #region Descriptor
    /// <summary>File descriptor for objects/collection.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CollectionReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhvYmplY3RzL2NvbGxlY3Rpb24ucHJvdG8SB29iamVjdHMiUQoOQ29sbGVj",
            "dGlvbkluZm8SCgoCaWQYASABKAMSDAoEbmFtZRgCIAEoCRISCgpjb3N0X211",
            "bGNoGAMgASgDEhEKCWNvc3RfZG9zaBgEIAEoAyJKCg5Db2xsZWN0aW9uSXRl",
            "bRIUCgxpdGVtX3R5cGVfaWQYASABKAMSDgoGcmFyaXR5GAIgASgJEhIKCm93",
            "bmVkQ291bnQYAyABKANCT1ovNTVwaXhlbHMuY29tL3d3c2VydmVyL2ludGVy",
            "bmFsL3Byb3RvYnVmL29iamVjdHOqAhtXZWV2aWxXb3JsZFByb3RvYnVmLk9i",
            "amVjdHM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::WeevilWorldProtobuf.Objects.CollectionInfo), global::WeevilWorldProtobuf.Objects.CollectionInfo.Parser, new[]{ "Id", "Name", "CostMulch", "CostDosh" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::WeevilWorldProtobuf.Objects.CollectionItem), global::WeevilWorldProtobuf.Objects.CollectionItem.Parser, new[]{ "ItemTypeId", "Rarity", "OwnedCount" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class CollectionInfo : pb::IMessage<CollectionInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CollectionInfo> _parser = new pb::MessageParser<CollectionInfo>(() => new CollectionInfo());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CollectionInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WeevilWorldProtobuf.Objects.CollectionReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CollectionInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CollectionInfo(CollectionInfo other) : this() {
      _hasBits0 = other._hasBits0;
      id_ = other.id_;
      name_ = other.name_;
      costMulch_ = other.costMulch_;
      costDosh_ = other.costDosh_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CollectionInfo Clone() {
      return new CollectionInfo(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private readonly static long IdDefaultValue = 0L;

    private long id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Id {
      get { if ((_hasBits0 & 1) != 0) { return id_; } else { return IdDefaultValue; } }
      set {
        _hasBits0 |= 1;
        id_ = value;
      }
    }
    /// <summary>Gets whether the "id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private readonly static string NameDefaultValue = "";

    private string name_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_ ?? NameDefaultValue; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "name" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasName {
      get { return name_ != null; }
    }
    /// <summary>Clears the value of the "name" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearName() {
      name_ = null;
    }

    /// <summary>Field number for the "cost_mulch" field.</summary>
    public const int CostMulchFieldNumber = 3;
    private readonly static long CostMulchDefaultValue = 0L;

    private long costMulch_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long CostMulch {
      get { if ((_hasBits0 & 2) != 0) { return costMulch_; } else { return CostMulchDefaultValue; } }
      set {
        _hasBits0 |= 2;
        costMulch_ = value;
      }
    }
    /// <summary>Gets whether the "cost_mulch" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasCostMulch {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "cost_mulch" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearCostMulch() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "cost_dosh" field.</summary>
    public const int CostDoshFieldNumber = 4;
    private readonly static long CostDoshDefaultValue = 0L;

    private long costDosh_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long CostDosh {
      get { if ((_hasBits0 & 4) != 0) { return costDosh_; } else { return CostDoshDefaultValue; } }
      set {
        _hasBits0 |= 4;
        costDosh_ = value;
      }
    }
    /// <summary>Gets whether the "cost_dosh" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasCostDosh {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "cost_dosh" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearCostDosh() {
      _hasBits0 &= ~4;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CollectionInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CollectionInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Name != other.Name) return false;
      if (CostMulch != other.CostMulch) return false;
      if (CostDosh != other.CostDosh) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasId) hash ^= Id.GetHashCode();
      if (HasName) hash ^= Name.GetHashCode();
      if (HasCostMulch) hash ^= CostMulch.GetHashCode();
      if (HasCostDosh) hash ^= CostDosh.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasId) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (HasName) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (HasCostMulch) {
        output.WriteRawTag(24);
        output.WriteInt64(CostMulch);
      }
      if (HasCostDosh) {
        output.WriteRawTag(32);
        output.WriteInt64(CostDosh);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasId) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (HasName) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (HasCostMulch) {
        output.WriteRawTag(24);
        output.WriteInt64(CostMulch);
      }
      if (HasCostDosh) {
        output.WriteRawTag(32);
        output.WriteInt64(CostDosh);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasId) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (HasName) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (HasCostMulch) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(CostMulch);
      }
      if (HasCostDosh) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(CostDosh);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CollectionInfo other) {
      if (other == null) {
        return;
      }
      if (other.HasId) {
        Id = other.Id;
      }
      if (other.HasName) {
        Name = other.Name;
      }
      if (other.HasCostMulch) {
        CostMulch = other.CostMulch;
      }
      if (other.HasCostDosh) {
        CostDosh = other.CostDosh;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 24: {
            CostMulch = input.ReadInt64();
            break;
          }
          case 32: {
            CostDosh = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 24: {
            CostMulch = input.ReadInt64();
            break;
          }
          case 32: {
            CostDosh = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CollectionItem : pb::IMessage<CollectionItem>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CollectionItem> _parser = new pb::MessageParser<CollectionItem>(() => new CollectionItem());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CollectionItem> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WeevilWorldProtobuf.Objects.CollectionReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CollectionItem() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CollectionItem(CollectionItem other) : this() {
      _hasBits0 = other._hasBits0;
      itemTypeId_ = other.itemTypeId_;
      rarity_ = other.rarity_;
      ownedCount_ = other.ownedCount_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CollectionItem Clone() {
      return new CollectionItem(this);
    }

    /// <summary>Field number for the "item_type_id" field.</summary>
    public const int ItemTypeIdFieldNumber = 1;
    private readonly static long ItemTypeIdDefaultValue = 0L;

    private long itemTypeId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long ItemTypeId {
      get { if ((_hasBits0 & 1) != 0) { return itemTypeId_; } else { return ItemTypeIdDefaultValue; } }
      set {
        _hasBits0 |= 1;
        itemTypeId_ = value;
      }
    }
    /// <summary>Gets whether the "item_type_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasItemTypeId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "item_type_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearItemTypeId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "rarity" field.</summary>
    public const int RarityFieldNumber = 2;
    private readonly static string RarityDefaultValue = "";

    private string rarity_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Rarity {
      get { return rarity_ ?? RarityDefaultValue; }
      set {
        rarity_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "rarity" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasRarity {
      get { return rarity_ != null; }
    }
    /// <summary>Clears the value of the "rarity" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearRarity() {
      rarity_ = null;
    }

    /// <summary>Field number for the "ownedCount" field.</summary>
    public const int OwnedCountFieldNumber = 3;
    private readonly static long OwnedCountDefaultValue = 0L;

    private long ownedCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long OwnedCount {
      get { if ((_hasBits0 & 2) != 0) { return ownedCount_; } else { return OwnedCountDefaultValue; } }
      set {
        _hasBits0 |= 2;
        ownedCount_ = value;
      }
    }
    /// <summary>Gets whether the "ownedCount" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasOwnedCount {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "ownedCount" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearOwnedCount() {
      _hasBits0 &= ~2;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CollectionItem);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CollectionItem other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ItemTypeId != other.ItemTypeId) return false;
      if (Rarity != other.Rarity) return false;
      if (OwnedCount != other.OwnedCount) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasItemTypeId) hash ^= ItemTypeId.GetHashCode();
      if (HasRarity) hash ^= Rarity.GetHashCode();
      if (HasOwnedCount) hash ^= OwnedCount.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasItemTypeId) {
        output.WriteRawTag(8);
        output.WriteInt64(ItemTypeId);
      }
      if (HasRarity) {
        output.WriteRawTag(18);
        output.WriteString(Rarity);
      }
      if (HasOwnedCount) {
        output.WriteRawTag(24);
        output.WriteInt64(OwnedCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasItemTypeId) {
        output.WriteRawTag(8);
        output.WriteInt64(ItemTypeId);
      }
      if (HasRarity) {
        output.WriteRawTag(18);
        output.WriteString(Rarity);
      }
      if (HasOwnedCount) {
        output.WriteRawTag(24);
        output.WriteInt64(OwnedCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasItemTypeId) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ItemTypeId);
      }
      if (HasRarity) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Rarity);
      }
      if (HasOwnedCount) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(OwnedCount);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CollectionItem other) {
      if (other == null) {
        return;
      }
      if (other.HasItemTypeId) {
        ItemTypeId = other.ItemTypeId;
      }
      if (other.HasRarity) {
        Rarity = other.Rarity;
      }
      if (other.HasOwnedCount) {
        OwnedCount = other.OwnedCount;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ItemTypeId = input.ReadInt64();
            break;
          }
          case 18: {
            Rarity = input.ReadString();
            break;
          }
          case 24: {
            OwnedCount = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ItemTypeId = input.ReadInt64();
            break;
          }
          case 18: {
            Rarity = input.ReadString();
            break;
          }
          case 24: {
            OwnedCount = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
