// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: objects/gift.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WeevilWorldProtobuf.Objects {

  /// <summary>Holder for reflection information generated from objects/gift.proto</summary>
  public static partial class GiftReflection {

    #region Descriptor
    /// <summary>File descriptor for objects/gift.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GiftReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJvYmplY3RzL2dpZnQucHJvdG8SB29iamVjdHMaFG9iamVjdHMvd2Vldmls",
            "LnByb3RvInIKBEdpZnQSCgoCSWQYASABKAMSIwoKRnJvbVdlZXZpbBgCIAEo",
            "CzIPLm9iamVjdHMuV2VldmlsEhIKCkl0ZW1UeXBlSWQYAyABKAMSDwoHTWVz",
            "c2FnZRgEIAEoCRIUCgxHaWZ0ZWRBdFVuaXgYBSABKANCT1ovNTVwaXhlbHMu",
            "Y29tL3d3c2VydmVyL2ludGVybmFsL3Byb3RvYnVmL29iamVjdHOqAhtXZWV2",
            "aWxXb3JsZFByb3RvYnVmLk9iamVjdHM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::WeevilWorldProtobuf.Objects.WeevilReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::WeevilWorldProtobuf.Objects.Gift), global::WeevilWorldProtobuf.Objects.Gift.Parser, new[]{ "Id", "FromWeevil", "ItemTypeId", "Message", "GiftedAtUnix" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Gift : pb::IMessage<Gift>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Gift> _parser = new pb::MessageParser<Gift>(() => new Gift());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Gift> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WeevilWorldProtobuf.Objects.GiftReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Gift() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Gift(Gift other) : this() {
      _hasBits0 = other._hasBits0;
      id_ = other.id_;
      fromWeevil_ = other.fromWeevil_ != null ? other.fromWeevil_.Clone() : null;
      itemTypeId_ = other.itemTypeId_;
      message_ = other.message_;
      giftedAtUnix_ = other.giftedAtUnix_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Gift Clone() {
      return new Gift(this);
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 1;
    private readonly static long IdDefaultValue = 0L;

    private long id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Id {
      get { if ((_hasBits0 & 1) != 0) { return id_; } else { return IdDefaultValue; } }
      set {
        _hasBits0 |= 1;
        id_ = value;
      }
    }
    /// <summary>Gets whether the "Id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "Id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "FromWeevil" field.</summary>
    public const int FromWeevilFieldNumber = 2;
    private global::WeevilWorldProtobuf.Objects.Weevil fromWeevil_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::WeevilWorldProtobuf.Objects.Weevil FromWeevil {
      get { return fromWeevil_; }
      set {
        fromWeevil_ = value;
      }
    }

    /// <summary>Field number for the "ItemTypeId" field.</summary>
    public const int ItemTypeIdFieldNumber = 3;
    private readonly static long ItemTypeIdDefaultValue = 0L;

    private long itemTypeId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long ItemTypeId {
      get { if ((_hasBits0 & 2) != 0) { return itemTypeId_; } else { return ItemTypeIdDefaultValue; } }
      set {
        _hasBits0 |= 2;
        itemTypeId_ = value;
      }
    }
    /// <summary>Gets whether the "ItemTypeId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasItemTypeId {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "ItemTypeId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearItemTypeId() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "Message" field.</summary>
    public const int MessageFieldNumber = 4;
    private readonly static string MessageDefaultValue = "";

    private string message_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Message {
      get { return message_ ?? MessageDefaultValue; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "Message" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasMessage {
      get { return message_ != null; }
    }
    /// <summary>Clears the value of the "Message" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearMessage() {
      message_ = null;
    }

    /// <summary>Field number for the "GiftedAtUnix" field.</summary>
    public const int GiftedAtUnixFieldNumber = 5;
    private readonly static long GiftedAtUnixDefaultValue = 0L;

    private long giftedAtUnix_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long GiftedAtUnix {
      get { if ((_hasBits0 & 4) != 0) { return giftedAtUnix_; } else { return GiftedAtUnixDefaultValue; } }
      set {
        _hasBits0 |= 4;
        giftedAtUnix_ = value;
      }
    }
    /// <summary>Gets whether the "GiftedAtUnix" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasGiftedAtUnix {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "GiftedAtUnix" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearGiftedAtUnix() {
      _hasBits0 &= ~4;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Gift);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Gift other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (!object.Equals(FromWeevil, other.FromWeevil)) return false;
      if (ItemTypeId != other.ItemTypeId) return false;
      if (Message != other.Message) return false;
      if (GiftedAtUnix != other.GiftedAtUnix) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasId) hash ^= Id.GetHashCode();
      if (fromWeevil_ != null) hash ^= FromWeevil.GetHashCode();
      if (HasItemTypeId) hash ^= ItemTypeId.GetHashCode();
      if (HasMessage) hash ^= Message.GetHashCode();
      if (HasGiftedAtUnix) hash ^= GiftedAtUnix.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasId) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (fromWeevil_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(FromWeevil);
      }
      if (HasItemTypeId) {
        output.WriteRawTag(24);
        output.WriteInt64(ItemTypeId);
      }
      if (HasMessage) {
        output.WriteRawTag(34);
        output.WriteString(Message);
      }
      if (HasGiftedAtUnix) {
        output.WriteRawTag(40);
        output.WriteInt64(GiftedAtUnix);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasId) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (fromWeevil_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(FromWeevil);
      }
      if (HasItemTypeId) {
        output.WriteRawTag(24);
        output.WriteInt64(ItemTypeId);
      }
      if (HasMessage) {
        output.WriteRawTag(34);
        output.WriteString(Message);
      }
      if (HasGiftedAtUnix) {
        output.WriteRawTag(40);
        output.WriteInt64(GiftedAtUnix);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasId) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (fromWeevil_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FromWeevil);
      }
      if (HasItemTypeId) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ItemTypeId);
      }
      if (HasMessage) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (HasGiftedAtUnix) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(GiftedAtUnix);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Gift other) {
      if (other == null) {
        return;
      }
      if (other.HasId) {
        Id = other.Id;
      }
      if (other.fromWeevil_ != null) {
        if (fromWeevil_ == null) {
          FromWeevil = new global::WeevilWorldProtobuf.Objects.Weevil();
        }
        FromWeevil.MergeFrom(other.FromWeevil);
      }
      if (other.HasItemTypeId) {
        ItemTypeId = other.ItemTypeId;
      }
      if (other.HasMessage) {
        Message = other.Message;
      }
      if (other.HasGiftedAtUnix) {
        GiftedAtUnix = other.GiftedAtUnix;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            if (fromWeevil_ == null) {
              FromWeevil = new global::WeevilWorldProtobuf.Objects.Weevil();
            }
            input.ReadMessage(FromWeevil);
            break;
          }
          case 24: {
            ItemTypeId = input.ReadInt64();
            break;
          }
          case 34: {
            Message = input.ReadString();
            break;
          }
          case 40: {
            GiftedAtUnix = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            if (fromWeevil_ == null) {
              FromWeevil = new global::WeevilWorldProtobuf.Objects.Weevil();
            }
            input.ReadMessage(FromWeevil);
            break;
          }
          case 24: {
            ItemTypeId = input.ReadInt64();
            break;
          }
          case 34: {
            Message = input.ReadString();
            break;
          }
          case 40: {
            GiftedAtUnix = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
