// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: objects/item.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WeevilWorldProtobuf.Objects {

  /// <summary>Holder for reflection information generated from objects/item.proto</summary>
  public static partial class ItemReflection {

    #region Descriptor
    /// <summary>File descriptor for objects/item.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ItemReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJvYmplY3RzL2l0ZW0ucHJvdG8SB29iamVjdHMi5gEKBEl0ZW0SCwoCSWQY",
            "tB8gASgDEg8KBlR5cGVJZBi1HyABKAMSDwoGUm9vbUlkGLYfIAEoAxIKCgFY",
            "GLcfIAEoAxIKCgFZGLgfIAEoAxIRCghQb3NpdGlvbhi5HyABKAMSEgoJV2Vh",
            "cmluZ0FzGLofIAEoAxIZChBJc01lbWJlcnNoaXBHaWZ0GLsfIAEoCBIWCg1V",
            "cGRhdGVkQXRVbml4GLwfIAEoAxILCgJYcBi/HyABKAMSFQoMQ29sbGVjdGlv",
            "bklEGL0fIAEoAxIZChBDb2xsZWN0aW9uUmFyaXR5GL4fIAEoCUJPWi81NXBp",
            "eGVscy5jb20vd3dzZXJ2ZXIvaW50ZXJuYWwvcHJvdG9idWYvb2JqZWN0c6oC",
            "G1dlZXZpbFdvcmxkUHJvdG9idWYuT2JqZWN0cw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::WeevilWorldProtobuf.Objects.Item), global::WeevilWorldProtobuf.Objects.Item.Parser, new[]{ "Id", "TypeId", "RoomId", "X", "Y", "Position", "WearingAs", "IsMembershipGift", "UpdatedAtUnix", "Xp", "CollectionID", "CollectionRarity" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Item : pb::IMessage<Item>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Item> _parser = new pb::MessageParser<Item>(() => new Item());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Item> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WeevilWorldProtobuf.Objects.ItemReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Item() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Item(Item other) : this() {
      _hasBits0 = other._hasBits0;
      id_ = other.id_;
      typeId_ = other.typeId_;
      roomId_ = other.roomId_;
      x_ = other.x_;
      y_ = other.y_;
      position_ = other.position_;
      wearingAs_ = other.wearingAs_;
      isMembershipGift_ = other.isMembershipGift_;
      updatedAtUnix_ = other.updatedAtUnix_;
      xp_ = other.xp_;
      collectionID_ = other.collectionID_;
      collectionRarity_ = other.collectionRarity_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Item Clone() {
      return new Item(this);
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 4020;
    private readonly static long IdDefaultValue = 0L;

    private long id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Id {
      get { if ((_hasBits0 & 1) != 0) { return id_; } else { return IdDefaultValue; } }
      set {
        _hasBits0 |= 1;
        id_ = value;
      }
    }
    /// <summary>Gets whether the "Id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "Id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "TypeId" field.</summary>
    public const int TypeIdFieldNumber = 4021;
    private readonly static long TypeIdDefaultValue = 0L;

    private long typeId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long TypeId {
      get { if ((_hasBits0 & 2) != 0) { return typeId_; } else { return TypeIdDefaultValue; } }
      set {
        _hasBits0 |= 2;
        typeId_ = value;
      }
    }
    /// <summary>Gets whether the "TypeId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasTypeId {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "TypeId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearTypeId() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "RoomId" field.</summary>
    public const int RoomIdFieldNumber = 4022;
    private readonly static long RoomIdDefaultValue = 0L;

    private long roomId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long RoomId {
      get { if ((_hasBits0 & 4) != 0) { return roomId_; } else { return RoomIdDefaultValue; } }
      set {
        _hasBits0 |= 4;
        roomId_ = value;
      }
    }
    /// <summary>Gets whether the "RoomId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasRoomId {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "RoomId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearRoomId() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "X" field.</summary>
    public const int XFieldNumber = 4023;
    private readonly static long XDefaultValue = 0L;

    private long x_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long X {
      get { if ((_hasBits0 & 8) != 0) { return x_; } else { return XDefaultValue; } }
      set {
        _hasBits0 |= 8;
        x_ = value;
      }
    }
    /// <summary>Gets whether the "X" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasX {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "X" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearX() {
      _hasBits0 &= ~8;
    }

    /// <summary>Field number for the "Y" field.</summary>
    public const int YFieldNumber = 4024;
    private readonly static long YDefaultValue = 0L;

    private long y_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Y {
      get { if ((_hasBits0 & 16) != 0) { return y_; } else { return YDefaultValue; } }
      set {
        _hasBits0 |= 16;
        y_ = value;
      }
    }
    /// <summary>Gets whether the "Y" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasY {
      get { return (_hasBits0 & 16) != 0; }
    }
    /// <summary>Clears the value of the "Y" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearY() {
      _hasBits0 &= ~16;
    }

    /// <summary>Field number for the "Position" field.</summary>
    public const int PositionFieldNumber = 4025;
    private readonly static long PositionDefaultValue = 0L;

    private long position_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Position {
      get { if ((_hasBits0 & 32) != 0) { return position_; } else { return PositionDefaultValue; } }
      set {
        _hasBits0 |= 32;
        position_ = value;
      }
    }
    /// <summary>Gets whether the "Position" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasPosition {
      get { return (_hasBits0 & 32) != 0; }
    }
    /// <summary>Clears the value of the "Position" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearPosition() {
      _hasBits0 &= ~32;
    }

    /// <summary>Field number for the "WearingAs" field.</summary>
    public const int WearingAsFieldNumber = 4026;
    private readonly static long WearingAsDefaultValue = 0L;

    private long wearingAs_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long WearingAs {
      get { if ((_hasBits0 & 64) != 0) { return wearingAs_; } else { return WearingAsDefaultValue; } }
      set {
        _hasBits0 |= 64;
        wearingAs_ = value;
      }
    }
    /// <summary>Gets whether the "WearingAs" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasWearingAs {
      get { return (_hasBits0 & 64) != 0; }
    }
    /// <summary>Clears the value of the "WearingAs" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearWearingAs() {
      _hasBits0 &= ~64;
    }

    /// <summary>Field number for the "IsMembershipGift" field.</summary>
    public const int IsMembershipGiftFieldNumber = 4027;
    private readonly static bool IsMembershipGiftDefaultValue = false;

    private bool isMembershipGift_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsMembershipGift {
      get { if ((_hasBits0 & 128) != 0) { return isMembershipGift_; } else { return IsMembershipGiftDefaultValue; } }
      set {
        _hasBits0 |= 128;
        isMembershipGift_ = value;
      }
    }
    /// <summary>Gets whether the "IsMembershipGift" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasIsMembershipGift {
      get { return (_hasBits0 & 128) != 0; }
    }
    /// <summary>Clears the value of the "IsMembershipGift" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearIsMembershipGift() {
      _hasBits0 &= ~128;
    }

    /// <summary>Field number for the "UpdatedAtUnix" field.</summary>
    public const int UpdatedAtUnixFieldNumber = 4028;
    private readonly static long UpdatedAtUnixDefaultValue = 0L;

    private long updatedAtUnix_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long UpdatedAtUnix {
      get { if ((_hasBits0 & 256) != 0) { return updatedAtUnix_; } else { return UpdatedAtUnixDefaultValue; } }
      set {
        _hasBits0 |= 256;
        updatedAtUnix_ = value;
      }
    }
    /// <summary>Gets whether the "UpdatedAtUnix" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasUpdatedAtUnix {
      get { return (_hasBits0 & 256) != 0; }
    }
    /// <summary>Clears the value of the "UpdatedAtUnix" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearUpdatedAtUnix() {
      _hasBits0 &= ~256;
    }

    /// <summary>Field number for the "Xp" field.</summary>
    public const int XpFieldNumber = 4031;
    private readonly static long XpDefaultValue = 0L;

    private long xp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Xp {
      get { if ((_hasBits0 & 1024) != 0) { return xp_; } else { return XpDefaultValue; } }
      set {
        _hasBits0 |= 1024;
        xp_ = value;
      }
    }
    /// <summary>Gets whether the "Xp" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasXp {
      get { return (_hasBits0 & 1024) != 0; }
    }
    /// <summary>Clears the value of the "Xp" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearXp() {
      _hasBits0 &= ~1024;
    }

    /// <summary>Field number for the "CollectionID" field.</summary>
    public const int CollectionIDFieldNumber = 4029;
    private readonly static long CollectionIDDefaultValue = 0L;

    private long collectionID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long CollectionID {
      get { if ((_hasBits0 & 512) != 0) { return collectionID_; } else { return CollectionIDDefaultValue; } }
      set {
        _hasBits0 |= 512;
        collectionID_ = value;
      }
    }
    /// <summary>Gets whether the "CollectionID" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasCollectionID {
      get { return (_hasBits0 & 512) != 0; }
    }
    /// <summary>Clears the value of the "CollectionID" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearCollectionID() {
      _hasBits0 &= ~512;
    }

    /// <summary>Field number for the "CollectionRarity" field.</summary>
    public const int CollectionRarityFieldNumber = 4030;
    private readonly static string CollectionRarityDefaultValue = "";

    private string collectionRarity_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CollectionRarity {
      get { return collectionRarity_ ?? CollectionRarityDefaultValue; }
      set {
        collectionRarity_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "CollectionRarity" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasCollectionRarity {
      get { return collectionRarity_ != null; }
    }
    /// <summary>Clears the value of the "CollectionRarity" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearCollectionRarity() {
      collectionRarity_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Item);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Item other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (TypeId != other.TypeId) return false;
      if (RoomId != other.RoomId) return false;
      if (X != other.X) return false;
      if (Y != other.Y) return false;
      if (Position != other.Position) return false;
      if (WearingAs != other.WearingAs) return false;
      if (IsMembershipGift != other.IsMembershipGift) return false;
      if (UpdatedAtUnix != other.UpdatedAtUnix) return false;
      if (Xp != other.Xp) return false;
      if (CollectionID != other.CollectionID) return false;
      if (CollectionRarity != other.CollectionRarity) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasId) hash ^= Id.GetHashCode();
      if (HasTypeId) hash ^= TypeId.GetHashCode();
      if (HasRoomId) hash ^= RoomId.GetHashCode();
      if (HasX) hash ^= X.GetHashCode();
      if (HasY) hash ^= Y.GetHashCode();
      if (HasPosition) hash ^= Position.GetHashCode();
      if (HasWearingAs) hash ^= WearingAs.GetHashCode();
      if (HasIsMembershipGift) hash ^= IsMembershipGift.GetHashCode();
      if (HasUpdatedAtUnix) hash ^= UpdatedAtUnix.GetHashCode();
      if (HasXp) hash ^= Xp.GetHashCode();
      if (HasCollectionID) hash ^= CollectionID.GetHashCode();
      if (HasCollectionRarity) hash ^= CollectionRarity.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasId) {
        output.WriteRawTag(160, 251, 1);
        output.WriteInt64(Id);
      }
      if (HasTypeId) {
        output.WriteRawTag(168, 251, 1);
        output.WriteInt64(TypeId);
      }
      if (HasRoomId) {
        output.WriteRawTag(176, 251, 1);
        output.WriteInt64(RoomId);
      }
      if (HasX) {
        output.WriteRawTag(184, 251, 1);
        output.WriteInt64(X);
      }
      if (HasY) {
        output.WriteRawTag(192, 251, 1);
        output.WriteInt64(Y);
      }
      if (HasPosition) {
        output.WriteRawTag(200, 251, 1);
        output.WriteInt64(Position);
      }
      if (HasWearingAs) {
        output.WriteRawTag(208, 251, 1);
        output.WriteInt64(WearingAs);
      }
      if (HasIsMembershipGift) {
        output.WriteRawTag(216, 251, 1);
        output.WriteBool(IsMembershipGift);
      }
      if (HasUpdatedAtUnix) {
        output.WriteRawTag(224, 251, 1);
        output.WriteInt64(UpdatedAtUnix);
      }
      if (HasCollectionID) {
        output.WriteRawTag(232, 251, 1);
        output.WriteInt64(CollectionID);
      }
      if (HasCollectionRarity) {
        output.WriteRawTag(242, 251, 1);
        output.WriteString(CollectionRarity);
      }
      if (HasXp) {
        output.WriteRawTag(248, 251, 1);
        output.WriteInt64(Xp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasId) {
        output.WriteRawTag(160, 251, 1);
        output.WriteInt64(Id);
      }
      if (HasTypeId) {
        output.WriteRawTag(168, 251, 1);
        output.WriteInt64(TypeId);
      }
      if (HasRoomId) {
        output.WriteRawTag(176, 251, 1);
        output.WriteInt64(RoomId);
      }
      if (HasX) {
        output.WriteRawTag(184, 251, 1);
        output.WriteInt64(X);
      }
      if (HasY) {
        output.WriteRawTag(192, 251, 1);
        output.WriteInt64(Y);
      }
      if (HasPosition) {
        output.WriteRawTag(200, 251, 1);
        output.WriteInt64(Position);
      }
      if (HasWearingAs) {
        output.WriteRawTag(208, 251, 1);
        output.WriteInt64(WearingAs);
      }
      if (HasIsMembershipGift) {
        output.WriteRawTag(216, 251, 1);
        output.WriteBool(IsMembershipGift);
      }
      if (HasUpdatedAtUnix) {
        output.WriteRawTag(224, 251, 1);
        output.WriteInt64(UpdatedAtUnix);
      }
      if (HasCollectionID) {
        output.WriteRawTag(232, 251, 1);
        output.WriteInt64(CollectionID);
      }
      if (HasCollectionRarity) {
        output.WriteRawTag(242, 251, 1);
        output.WriteString(CollectionRarity);
      }
      if (HasXp) {
        output.WriteRawTag(248, 251, 1);
        output.WriteInt64(Xp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasId) {
        size += 3 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (HasTypeId) {
        size += 3 + pb::CodedOutputStream.ComputeInt64Size(TypeId);
      }
      if (HasRoomId) {
        size += 3 + pb::CodedOutputStream.ComputeInt64Size(RoomId);
      }
      if (HasX) {
        size += 3 + pb::CodedOutputStream.ComputeInt64Size(X);
      }
      if (HasY) {
        size += 3 + pb::CodedOutputStream.ComputeInt64Size(Y);
      }
      if (HasPosition) {
        size += 3 + pb::CodedOutputStream.ComputeInt64Size(Position);
      }
      if (HasWearingAs) {
        size += 3 + pb::CodedOutputStream.ComputeInt64Size(WearingAs);
      }
      if (HasIsMembershipGift) {
        size += 3 + 1;
      }
      if (HasUpdatedAtUnix) {
        size += 3 + pb::CodedOutputStream.ComputeInt64Size(UpdatedAtUnix);
      }
      if (HasXp) {
        size += 3 + pb::CodedOutputStream.ComputeInt64Size(Xp);
      }
      if (HasCollectionID) {
        size += 3 + pb::CodedOutputStream.ComputeInt64Size(CollectionID);
      }
      if (HasCollectionRarity) {
        size += 3 + pb::CodedOutputStream.ComputeStringSize(CollectionRarity);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Item other) {
      if (other == null) {
        return;
      }
      if (other.HasId) {
        Id = other.Id;
      }
      if (other.HasTypeId) {
        TypeId = other.TypeId;
      }
      if (other.HasRoomId) {
        RoomId = other.RoomId;
      }
      if (other.HasX) {
        X = other.X;
      }
      if (other.HasY) {
        Y = other.Y;
      }
      if (other.HasPosition) {
        Position = other.Position;
      }
      if (other.HasWearingAs) {
        WearingAs = other.WearingAs;
      }
      if (other.HasIsMembershipGift) {
        IsMembershipGift = other.IsMembershipGift;
      }
      if (other.HasUpdatedAtUnix) {
        UpdatedAtUnix = other.UpdatedAtUnix;
      }
      if (other.HasXp) {
        Xp = other.Xp;
      }
      if (other.HasCollectionID) {
        CollectionID = other.CollectionID;
      }
      if (other.HasCollectionRarity) {
        CollectionRarity = other.CollectionRarity;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 32160: {
            Id = input.ReadInt64();
            break;
          }
          case 32168: {
            TypeId = input.ReadInt64();
            break;
          }
          case 32176: {
            RoomId = input.ReadInt64();
            break;
          }
          case 32184: {
            X = input.ReadInt64();
            break;
          }
          case 32192: {
            Y = input.ReadInt64();
            break;
          }
          case 32200: {
            Position = input.ReadInt64();
            break;
          }
          case 32208: {
            WearingAs = input.ReadInt64();
            break;
          }
          case 32216: {
            IsMembershipGift = input.ReadBool();
            break;
          }
          case 32224: {
            UpdatedAtUnix = input.ReadInt64();
            break;
          }
          case 32232: {
            CollectionID = input.ReadInt64();
            break;
          }
          case 32242: {
            CollectionRarity = input.ReadString();
            break;
          }
          case 32248: {
            Xp = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 32160: {
            Id = input.ReadInt64();
            break;
          }
          case 32168: {
            TypeId = input.ReadInt64();
            break;
          }
          case 32176: {
            RoomId = input.ReadInt64();
            break;
          }
          case 32184: {
            X = input.ReadInt64();
            break;
          }
          case 32192: {
            Y = input.ReadInt64();
            break;
          }
          case 32200: {
            Position = input.ReadInt64();
            break;
          }
          case 32208: {
            WearingAs = input.ReadInt64();
            break;
          }
          case 32216: {
            IsMembershipGift = input.ReadBool();
            break;
          }
          case 32224: {
            UpdatedAtUnix = input.ReadInt64();
            break;
          }
          case 32232: {
            CollectionID = input.ReadInt64();
            break;
          }
          case 32242: {
            CollectionRarity = input.ReadString();
            break;
          }
          case 32248: {
            Xp = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
