// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: objects/treasure_hunt.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WeevilWorldProtobuf.Objects {

  /// <summary>Holder for reflection information generated from objects/treasure_hunt.proto</summary>
  public static partial class TreasureHuntReflection {

    #region Descriptor
    /// <summary>File descriptor for objects/treasure_hunt.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TreasureHuntReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChtvYmplY3RzL3RyZWFzdXJlX2h1bnQucHJvdG8SB29iamVjdHMaGWVudW1z",
            "L3RyZWFzdXJlX2h1bnQucHJvdG8iUAoVVHJlYXN1cmVIdW50X09ic3RhY2xl",
            "EgsKA1JvdxgBIAEoAxILCgNDb2wYAiABKAMSDQoFV2lkdGgYAyABKAMSDgoG",
            "SGVpZ2h0GAQgASgDIl4KEFRyZWFzdXJlSHVudF9NYXASDQoFV2lkdGgYASAB",
            "KAMSDgoGSGVpZ2h0GAIgASgDEisKBVRpbGVzGAMgAygOMhwuZW51bXMuVHJl",
            "YXN1cmVIdW50X1RpbGVUeXBlIl0KEVRyZWFzdXJlSHVudF9IaW50EgsKA1Jv",
            "dxgBIAEoAxILCgNDb2wYAiABKAMSLgoESGludBgDIAEoDjIcLmVudW1zLlRy",
            "ZWFzdXJlSHVudF9UaWxlSGludDoCTm8iowEKFlRyZWFzdXJlSHVudF9EaWdS",
            "ZXN1bHQSOAoGcmVzdWx0GAEgASgOMh0uZW51bXMuVHJlYXN1cmVIdW50X0Rp",
            "Z1Jlc3VsdDoJQ2Fubm90RGlnEikKBWhpbnRzGAIgAygLMhoub2JqZWN0cy5U",
            "cmVhc3VyZUh1bnRfSGludBISCgpwYXJ0TnVtYmVyGAMgASgDEhAKCGl0ZW1U",
            "eXBlGAQgASgDIlkKF1RyZWFzdXJlSHVudF9TaG92ZWxQYWNrEgwKBG5hbWUY",
            "ASABKAkSDwoHc2hvdmVscxgCIAEoAxINCgVwcmljZRgDIAEoAxIQCghjdXJy",
            "ZW5jeRgEIAEoAyLOAgoVVHJlYXN1cmVIdW50X0FyZWFJbmZvEhoKEm1haW5J",
            "dGVtUGFydHNGb3VuZBgBIAMoAxIeChZyZWd1bGFySXRlbXNUeXBlc0ZvdW5k",
            "GAIgAygDEhoKEnJhcmVJdGVtVHlwZXNGb3VuZBgDIAMoAxIaChJ0b3RhbE1h",
            "aW5JdGVtUGFydHMYBCABKAMSIQoZdG90YWxSZWd1bGFySXRlbVR5cGVDb3Vu",
            "dBgFIAEoAxIeChZ0b3RhbFJhcmVJdGVtVHlwZUNvdW50GAYgASgDEhcKD2l0",
            "ZW1UeXBlc1RvRmluZBgHIAMoAxIUCgxtYWluSXRlbVR5cGUYCCABKAMSHgoW",
            "cmVndWxhckl0ZW1UeXBlc1RvRmluZBgJIAMoAxIbChNyYXJlSXRlbVR5cGVz",
            "VG9GaW5kGAogAygDEhIKCnR5Y29vbk9ubHkYCyABKAhCT1ovNTVwaXhlbHMu",
            "Y29tL3d3c2VydmVyL2ludGVybmFsL3Byb3RvYnVmL29iamVjdHOqAhtXZWV2",
            "aWxXb3JsZFByb3RvYnVmLk9iamVjdHM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::WeevilWorldProtobuf.Enums.TreasureHuntReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::WeevilWorldProtobuf.Objects.TreasureHunt_Obstacle), global::WeevilWorldProtobuf.Objects.TreasureHunt_Obstacle.Parser, new[]{ "Row", "Col", "Width", "Height" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::WeevilWorldProtobuf.Objects.TreasureHunt_Map), global::WeevilWorldProtobuf.Objects.TreasureHunt_Map.Parser, new[]{ "Width", "Height", "Tiles" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::WeevilWorldProtobuf.Objects.TreasureHunt_Hint), global::WeevilWorldProtobuf.Objects.TreasureHunt_Hint.Parser, new[]{ "Row", "Col", "Hint" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::WeevilWorldProtobuf.Objects.TreasureHunt_DigResult), global::WeevilWorldProtobuf.Objects.TreasureHunt_DigResult.Parser, new[]{ "Result", "Hints", "PartNumber", "ItemType" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::WeevilWorldProtobuf.Objects.TreasureHunt_ShovelPack), global::WeevilWorldProtobuf.Objects.TreasureHunt_ShovelPack.Parser, new[]{ "Name", "Shovels", "Price", "Currency" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::WeevilWorldProtobuf.Objects.TreasureHunt_AreaInfo), global::WeevilWorldProtobuf.Objects.TreasureHunt_AreaInfo.Parser, new[]{ "MainItemPartsFound", "RegularItemsTypesFound", "RareItemTypesFound", "TotalMainItemParts", "TotalRegularItemTypeCount", "TotalRareItemTypeCount", "ItemTypesToFind", "MainItemType", "RegularItemTypesToFind", "RareItemTypesToFind", "TycoonOnly" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class TreasureHunt_Obstacle : pb::IMessage<TreasureHunt_Obstacle>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TreasureHunt_Obstacle> _parser = new pb::MessageParser<TreasureHunt_Obstacle>(() => new TreasureHunt_Obstacle());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TreasureHunt_Obstacle> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WeevilWorldProtobuf.Objects.TreasureHuntReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TreasureHunt_Obstacle() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TreasureHunt_Obstacle(TreasureHunt_Obstacle other) : this() {
      _hasBits0 = other._hasBits0;
      row_ = other.row_;
      col_ = other.col_;
      width_ = other.width_;
      height_ = other.height_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TreasureHunt_Obstacle Clone() {
      return new TreasureHunt_Obstacle(this);
    }

    /// <summary>Field number for the "Row" field.</summary>
    public const int RowFieldNumber = 1;
    private readonly static long RowDefaultValue = 0L;

    private long row_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Row {
      get { if ((_hasBits0 & 1) != 0) { return row_; } else { return RowDefaultValue; } }
      set {
        _hasBits0 |= 1;
        row_ = value;
      }
    }
    /// <summary>Gets whether the "Row" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasRow {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "Row" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearRow() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "Col" field.</summary>
    public const int ColFieldNumber = 2;
    private readonly static long ColDefaultValue = 0L;

    private long col_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Col {
      get { if ((_hasBits0 & 2) != 0) { return col_; } else { return ColDefaultValue; } }
      set {
        _hasBits0 |= 2;
        col_ = value;
      }
    }
    /// <summary>Gets whether the "Col" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasCol {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "Col" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearCol() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "Width" field.</summary>
    public const int WidthFieldNumber = 3;
    private readonly static long WidthDefaultValue = 0L;

    private long width_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Width {
      get { if ((_hasBits0 & 4) != 0) { return width_; } else { return WidthDefaultValue; } }
      set {
        _hasBits0 |= 4;
        width_ = value;
      }
    }
    /// <summary>Gets whether the "Width" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasWidth {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "Width" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearWidth() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "Height" field.</summary>
    public const int HeightFieldNumber = 4;
    private readonly static long HeightDefaultValue = 0L;

    private long height_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Height {
      get { if ((_hasBits0 & 8) != 0) { return height_; } else { return HeightDefaultValue; } }
      set {
        _hasBits0 |= 8;
        height_ = value;
      }
    }
    /// <summary>Gets whether the "Height" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasHeight {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "Height" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearHeight() {
      _hasBits0 &= ~8;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as TreasureHunt_Obstacle);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TreasureHunt_Obstacle other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Row != other.Row) return false;
      if (Col != other.Col) return false;
      if (Width != other.Width) return false;
      if (Height != other.Height) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasRow) hash ^= Row.GetHashCode();
      if (HasCol) hash ^= Col.GetHashCode();
      if (HasWidth) hash ^= Width.GetHashCode();
      if (HasHeight) hash ^= Height.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasRow) {
        output.WriteRawTag(8);
        output.WriteInt64(Row);
      }
      if (HasCol) {
        output.WriteRawTag(16);
        output.WriteInt64(Col);
      }
      if (HasWidth) {
        output.WriteRawTag(24);
        output.WriteInt64(Width);
      }
      if (HasHeight) {
        output.WriteRawTag(32);
        output.WriteInt64(Height);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasRow) {
        output.WriteRawTag(8);
        output.WriteInt64(Row);
      }
      if (HasCol) {
        output.WriteRawTag(16);
        output.WriteInt64(Col);
      }
      if (HasWidth) {
        output.WriteRawTag(24);
        output.WriteInt64(Width);
      }
      if (HasHeight) {
        output.WriteRawTag(32);
        output.WriteInt64(Height);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasRow) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Row);
      }
      if (HasCol) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Col);
      }
      if (HasWidth) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Width);
      }
      if (HasHeight) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Height);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TreasureHunt_Obstacle other) {
      if (other == null) {
        return;
      }
      if (other.HasRow) {
        Row = other.Row;
      }
      if (other.HasCol) {
        Col = other.Col;
      }
      if (other.HasWidth) {
        Width = other.Width;
      }
      if (other.HasHeight) {
        Height = other.Height;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Row = input.ReadInt64();
            break;
          }
          case 16: {
            Col = input.ReadInt64();
            break;
          }
          case 24: {
            Width = input.ReadInt64();
            break;
          }
          case 32: {
            Height = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Row = input.ReadInt64();
            break;
          }
          case 16: {
            Col = input.ReadInt64();
            break;
          }
          case 24: {
            Width = input.ReadInt64();
            break;
          }
          case 32: {
            Height = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class TreasureHunt_Map : pb::IMessage<TreasureHunt_Map>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TreasureHunt_Map> _parser = new pb::MessageParser<TreasureHunt_Map>(() => new TreasureHunt_Map());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TreasureHunt_Map> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WeevilWorldProtobuf.Objects.TreasureHuntReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TreasureHunt_Map() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TreasureHunt_Map(TreasureHunt_Map other) : this() {
      _hasBits0 = other._hasBits0;
      width_ = other.width_;
      height_ = other.height_;
      tiles_ = other.tiles_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TreasureHunt_Map Clone() {
      return new TreasureHunt_Map(this);
    }

    /// <summary>Field number for the "Width" field.</summary>
    public const int WidthFieldNumber = 1;
    private readonly static long WidthDefaultValue = 0L;

    private long width_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Width {
      get { if ((_hasBits0 & 1) != 0) { return width_; } else { return WidthDefaultValue; } }
      set {
        _hasBits0 |= 1;
        width_ = value;
      }
    }
    /// <summary>Gets whether the "Width" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasWidth {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "Width" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearWidth() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "Height" field.</summary>
    public const int HeightFieldNumber = 2;
    private readonly static long HeightDefaultValue = 0L;

    private long height_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Height {
      get { if ((_hasBits0 & 2) != 0) { return height_; } else { return HeightDefaultValue; } }
      set {
        _hasBits0 |= 2;
        height_ = value;
      }
    }
    /// <summary>Gets whether the "Height" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasHeight {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "Height" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearHeight() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "Tiles" field.</summary>
    public const int TilesFieldNumber = 3;
    private static readonly pb::FieldCodec<global::WeevilWorldProtobuf.Enums.TreasureHunt_TileType> _repeated_tiles_codec
        = pb::FieldCodec.ForEnum(24, x => (int) x, x => (global::WeevilWorldProtobuf.Enums.TreasureHunt_TileType) x);
    private readonly pbc::RepeatedField<global::WeevilWorldProtobuf.Enums.TreasureHunt_TileType> tiles_ = new pbc::RepeatedField<global::WeevilWorldProtobuf.Enums.TreasureHunt_TileType>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::WeevilWorldProtobuf.Enums.TreasureHunt_TileType> Tiles {
      get { return tiles_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as TreasureHunt_Map);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TreasureHunt_Map other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Width != other.Width) return false;
      if (Height != other.Height) return false;
      if(!tiles_.Equals(other.tiles_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasWidth) hash ^= Width.GetHashCode();
      if (HasHeight) hash ^= Height.GetHashCode();
      hash ^= tiles_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasWidth) {
        output.WriteRawTag(8);
        output.WriteInt64(Width);
      }
      if (HasHeight) {
        output.WriteRawTag(16);
        output.WriteInt64(Height);
      }
      tiles_.WriteTo(output, _repeated_tiles_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasWidth) {
        output.WriteRawTag(8);
        output.WriteInt64(Width);
      }
      if (HasHeight) {
        output.WriteRawTag(16);
        output.WriteInt64(Height);
      }
      tiles_.WriteTo(ref output, _repeated_tiles_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasWidth) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Width);
      }
      if (HasHeight) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Height);
      }
      size += tiles_.CalculateSize(_repeated_tiles_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TreasureHunt_Map other) {
      if (other == null) {
        return;
      }
      if (other.HasWidth) {
        Width = other.Width;
      }
      if (other.HasHeight) {
        Height = other.Height;
      }
      tiles_.Add(other.tiles_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Width = input.ReadInt64();
            break;
          }
          case 16: {
            Height = input.ReadInt64();
            break;
          }
          case 26:
          case 24: {
            tiles_.AddEntriesFrom(input, _repeated_tiles_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Width = input.ReadInt64();
            break;
          }
          case 16: {
            Height = input.ReadInt64();
            break;
          }
          case 26:
          case 24: {
            tiles_.AddEntriesFrom(ref input, _repeated_tiles_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class TreasureHunt_Hint : pb::IMessage<TreasureHunt_Hint>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TreasureHunt_Hint> _parser = new pb::MessageParser<TreasureHunt_Hint>(() => new TreasureHunt_Hint());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TreasureHunt_Hint> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WeevilWorldProtobuf.Objects.TreasureHuntReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TreasureHunt_Hint() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TreasureHunt_Hint(TreasureHunt_Hint other) : this() {
      _hasBits0 = other._hasBits0;
      row_ = other.row_;
      col_ = other.col_;
      hint_ = other.hint_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TreasureHunt_Hint Clone() {
      return new TreasureHunt_Hint(this);
    }

    /// <summary>Field number for the "Row" field.</summary>
    public const int RowFieldNumber = 1;
    private readonly static long RowDefaultValue = 0L;

    private long row_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Row {
      get { if ((_hasBits0 & 1) != 0) { return row_; } else { return RowDefaultValue; } }
      set {
        _hasBits0 |= 1;
        row_ = value;
      }
    }
    /// <summary>Gets whether the "Row" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasRow {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "Row" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearRow() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "Col" field.</summary>
    public const int ColFieldNumber = 2;
    private readonly static long ColDefaultValue = 0L;

    private long col_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Col {
      get { if ((_hasBits0 & 2) != 0) { return col_; } else { return ColDefaultValue; } }
      set {
        _hasBits0 |= 2;
        col_ = value;
      }
    }
    /// <summary>Gets whether the "Col" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasCol {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "Col" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearCol() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "Hint" field.</summary>
    public const int HintFieldNumber = 3;
    private readonly static global::WeevilWorldProtobuf.Enums.TreasureHunt_TileHint HintDefaultValue = global::WeevilWorldProtobuf.Enums.TreasureHunt_TileHint.No;

    private global::WeevilWorldProtobuf.Enums.TreasureHunt_TileHint hint_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::WeevilWorldProtobuf.Enums.TreasureHunt_TileHint Hint {
      get { if ((_hasBits0 & 4) != 0) { return hint_; } else { return HintDefaultValue; } }
      set {
        _hasBits0 |= 4;
        hint_ = value;
      }
    }
    /// <summary>Gets whether the "Hint" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasHint {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "Hint" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearHint() {
      _hasBits0 &= ~4;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as TreasureHunt_Hint);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TreasureHunt_Hint other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Row != other.Row) return false;
      if (Col != other.Col) return false;
      if (Hint != other.Hint) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasRow) hash ^= Row.GetHashCode();
      if (HasCol) hash ^= Col.GetHashCode();
      if (HasHint) hash ^= Hint.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasRow) {
        output.WriteRawTag(8);
        output.WriteInt64(Row);
      }
      if (HasCol) {
        output.WriteRawTag(16);
        output.WriteInt64(Col);
      }
      if (HasHint) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Hint);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasRow) {
        output.WriteRawTag(8);
        output.WriteInt64(Row);
      }
      if (HasCol) {
        output.WriteRawTag(16);
        output.WriteInt64(Col);
      }
      if (HasHint) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Hint);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasRow) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Row);
      }
      if (HasCol) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Col);
      }
      if (HasHint) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Hint);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TreasureHunt_Hint other) {
      if (other == null) {
        return;
      }
      if (other.HasRow) {
        Row = other.Row;
      }
      if (other.HasCol) {
        Col = other.Col;
      }
      if (other.HasHint) {
        Hint = other.Hint;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Row = input.ReadInt64();
            break;
          }
          case 16: {
            Col = input.ReadInt64();
            break;
          }
          case 24: {
            Hint = (global::WeevilWorldProtobuf.Enums.TreasureHunt_TileHint) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Row = input.ReadInt64();
            break;
          }
          case 16: {
            Col = input.ReadInt64();
            break;
          }
          case 24: {
            Hint = (global::WeevilWorldProtobuf.Enums.TreasureHunt_TileHint) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class TreasureHunt_DigResult : pb::IMessage<TreasureHunt_DigResult>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TreasureHunt_DigResult> _parser = new pb::MessageParser<TreasureHunt_DigResult>(() => new TreasureHunt_DigResult());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TreasureHunt_DigResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WeevilWorldProtobuf.Objects.TreasureHuntReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TreasureHunt_DigResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TreasureHunt_DigResult(TreasureHunt_DigResult other) : this() {
      _hasBits0 = other._hasBits0;
      result_ = other.result_;
      hints_ = other.hints_.Clone();
      partNumber_ = other.partNumber_;
      itemType_ = other.itemType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TreasureHunt_DigResult Clone() {
      return new TreasureHunt_DigResult(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private readonly static global::WeevilWorldProtobuf.Enums.TreasureHunt_DigResult ResultDefaultValue = global::WeevilWorldProtobuf.Enums.TreasureHunt_DigResult.CannotDig;

    private global::WeevilWorldProtobuf.Enums.TreasureHunt_DigResult result_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::WeevilWorldProtobuf.Enums.TreasureHunt_DigResult Result {
      get { if ((_hasBits0 & 1) != 0) { return result_; } else { return ResultDefaultValue; } }
      set {
        _hasBits0 |= 1;
        result_ = value;
      }
    }
    /// <summary>Gets whether the "result" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasResult {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "result" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearResult() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "hints" field.</summary>
    public const int HintsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::WeevilWorldProtobuf.Objects.TreasureHunt_Hint> _repeated_hints_codec
        = pb::FieldCodec.ForMessage(18, global::WeevilWorldProtobuf.Objects.TreasureHunt_Hint.Parser);
    private readonly pbc::RepeatedField<global::WeevilWorldProtobuf.Objects.TreasureHunt_Hint> hints_ = new pbc::RepeatedField<global::WeevilWorldProtobuf.Objects.TreasureHunt_Hint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::WeevilWorldProtobuf.Objects.TreasureHunt_Hint> Hints {
      get { return hints_; }
    }

    /// <summary>Field number for the "partNumber" field.</summary>
    public const int PartNumberFieldNumber = 3;
    private readonly static long PartNumberDefaultValue = 0L;

    private long partNumber_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long PartNumber {
      get { if ((_hasBits0 & 2) != 0) { return partNumber_; } else { return PartNumberDefaultValue; } }
      set {
        _hasBits0 |= 2;
        partNumber_ = value;
      }
    }
    /// <summary>Gets whether the "partNumber" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasPartNumber {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "partNumber" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearPartNumber() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "itemType" field.</summary>
    public const int ItemTypeFieldNumber = 4;
    private readonly static long ItemTypeDefaultValue = 0L;

    private long itemType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long ItemType {
      get { if ((_hasBits0 & 4) != 0) { return itemType_; } else { return ItemTypeDefaultValue; } }
      set {
        _hasBits0 |= 4;
        itemType_ = value;
      }
    }
    /// <summary>Gets whether the "itemType" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasItemType {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "itemType" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearItemType() {
      _hasBits0 &= ~4;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as TreasureHunt_DigResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TreasureHunt_DigResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Result != other.Result) return false;
      if(!hints_.Equals(other.hints_)) return false;
      if (PartNumber != other.PartNumber) return false;
      if (ItemType != other.ItemType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasResult) hash ^= Result.GetHashCode();
      hash ^= hints_.GetHashCode();
      if (HasPartNumber) hash ^= PartNumber.GetHashCode();
      if (HasItemType) hash ^= ItemType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasResult) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Result);
      }
      hints_.WriteTo(output, _repeated_hints_codec);
      if (HasPartNumber) {
        output.WriteRawTag(24);
        output.WriteInt64(PartNumber);
      }
      if (HasItemType) {
        output.WriteRawTag(32);
        output.WriteInt64(ItemType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasResult) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Result);
      }
      hints_.WriteTo(ref output, _repeated_hints_codec);
      if (HasPartNumber) {
        output.WriteRawTag(24);
        output.WriteInt64(PartNumber);
      }
      if (HasItemType) {
        output.WriteRawTag(32);
        output.WriteInt64(ItemType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasResult) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Result);
      }
      size += hints_.CalculateSize(_repeated_hints_codec);
      if (HasPartNumber) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(PartNumber);
      }
      if (HasItemType) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ItemType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TreasureHunt_DigResult other) {
      if (other == null) {
        return;
      }
      if (other.HasResult) {
        Result = other.Result;
      }
      hints_.Add(other.hints_);
      if (other.HasPartNumber) {
        PartNumber = other.PartNumber;
      }
      if (other.HasItemType) {
        ItemType = other.ItemType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Result = (global::WeevilWorldProtobuf.Enums.TreasureHunt_DigResult) input.ReadEnum();
            break;
          }
          case 18: {
            hints_.AddEntriesFrom(input, _repeated_hints_codec);
            break;
          }
          case 24: {
            PartNumber = input.ReadInt64();
            break;
          }
          case 32: {
            ItemType = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Result = (global::WeevilWorldProtobuf.Enums.TreasureHunt_DigResult) input.ReadEnum();
            break;
          }
          case 18: {
            hints_.AddEntriesFrom(ref input, _repeated_hints_codec);
            break;
          }
          case 24: {
            PartNumber = input.ReadInt64();
            break;
          }
          case 32: {
            ItemType = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class TreasureHunt_ShovelPack : pb::IMessage<TreasureHunt_ShovelPack>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TreasureHunt_ShovelPack> _parser = new pb::MessageParser<TreasureHunt_ShovelPack>(() => new TreasureHunt_ShovelPack());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TreasureHunt_ShovelPack> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WeevilWorldProtobuf.Objects.TreasureHuntReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TreasureHunt_ShovelPack() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TreasureHunt_ShovelPack(TreasureHunt_ShovelPack other) : this() {
      _hasBits0 = other._hasBits0;
      name_ = other.name_;
      shovels_ = other.shovels_;
      price_ = other.price_;
      currency_ = other.currency_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TreasureHunt_ShovelPack Clone() {
      return new TreasureHunt_ShovelPack(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private readonly static string NameDefaultValue = "";

    private string name_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_ ?? NameDefaultValue; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "name" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasName {
      get { return name_ != null; }
    }
    /// <summary>Clears the value of the "name" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearName() {
      name_ = null;
    }

    /// <summary>Field number for the "shovels" field.</summary>
    public const int ShovelsFieldNumber = 2;
    private readonly static long ShovelsDefaultValue = 0L;

    private long shovels_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Shovels {
      get { if ((_hasBits0 & 1) != 0) { return shovels_; } else { return ShovelsDefaultValue; } }
      set {
        _hasBits0 |= 1;
        shovels_ = value;
      }
    }
    /// <summary>Gets whether the "shovels" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasShovels {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "shovels" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearShovels() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "price" field.</summary>
    public const int PriceFieldNumber = 3;
    private readonly static long PriceDefaultValue = 0L;

    private long price_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Price {
      get { if ((_hasBits0 & 2) != 0) { return price_; } else { return PriceDefaultValue; } }
      set {
        _hasBits0 |= 2;
        price_ = value;
      }
    }
    /// <summary>Gets whether the "price" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasPrice {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "price" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearPrice() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "currency" field.</summary>
    public const int CurrencyFieldNumber = 4;
    private readonly static long CurrencyDefaultValue = 0L;

    private long currency_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Currency {
      get { if ((_hasBits0 & 4) != 0) { return currency_; } else { return CurrencyDefaultValue; } }
      set {
        _hasBits0 |= 4;
        currency_ = value;
      }
    }
    /// <summary>Gets whether the "currency" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasCurrency {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "currency" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearCurrency() {
      _hasBits0 &= ~4;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as TreasureHunt_ShovelPack);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TreasureHunt_ShovelPack other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Shovels != other.Shovels) return false;
      if (Price != other.Price) return false;
      if (Currency != other.Currency) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasName) hash ^= Name.GetHashCode();
      if (HasShovels) hash ^= Shovels.GetHashCode();
      if (HasPrice) hash ^= Price.GetHashCode();
      if (HasCurrency) hash ^= Currency.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasName) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (HasShovels) {
        output.WriteRawTag(16);
        output.WriteInt64(Shovels);
      }
      if (HasPrice) {
        output.WriteRawTag(24);
        output.WriteInt64(Price);
      }
      if (HasCurrency) {
        output.WriteRawTag(32);
        output.WriteInt64(Currency);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasName) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (HasShovels) {
        output.WriteRawTag(16);
        output.WriteInt64(Shovels);
      }
      if (HasPrice) {
        output.WriteRawTag(24);
        output.WriteInt64(Price);
      }
      if (HasCurrency) {
        output.WriteRawTag(32);
        output.WriteInt64(Currency);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasName) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (HasShovels) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Shovels);
      }
      if (HasPrice) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Price);
      }
      if (HasCurrency) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Currency);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TreasureHunt_ShovelPack other) {
      if (other == null) {
        return;
      }
      if (other.HasName) {
        Name = other.Name;
      }
      if (other.HasShovels) {
        Shovels = other.Shovels;
      }
      if (other.HasPrice) {
        Price = other.Price;
      }
      if (other.HasCurrency) {
        Currency = other.Currency;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            Shovels = input.ReadInt64();
            break;
          }
          case 24: {
            Price = input.ReadInt64();
            break;
          }
          case 32: {
            Currency = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            Shovels = input.ReadInt64();
            break;
          }
          case 24: {
            Price = input.ReadInt64();
            break;
          }
          case 32: {
            Currency = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class TreasureHunt_AreaInfo : pb::IMessage<TreasureHunt_AreaInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TreasureHunt_AreaInfo> _parser = new pb::MessageParser<TreasureHunt_AreaInfo>(() => new TreasureHunt_AreaInfo());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TreasureHunt_AreaInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WeevilWorldProtobuf.Objects.TreasureHuntReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TreasureHunt_AreaInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TreasureHunt_AreaInfo(TreasureHunt_AreaInfo other) : this() {
      _hasBits0 = other._hasBits0;
      mainItemPartsFound_ = other.mainItemPartsFound_.Clone();
      regularItemsTypesFound_ = other.regularItemsTypesFound_.Clone();
      rareItemTypesFound_ = other.rareItemTypesFound_.Clone();
      totalMainItemParts_ = other.totalMainItemParts_;
      totalRegularItemTypeCount_ = other.totalRegularItemTypeCount_;
      totalRareItemTypeCount_ = other.totalRareItemTypeCount_;
      itemTypesToFind_ = other.itemTypesToFind_.Clone();
      mainItemType_ = other.mainItemType_;
      regularItemTypesToFind_ = other.regularItemTypesToFind_.Clone();
      rareItemTypesToFind_ = other.rareItemTypesToFind_.Clone();
      tycoonOnly_ = other.tycoonOnly_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TreasureHunt_AreaInfo Clone() {
      return new TreasureHunt_AreaInfo(this);
    }

    /// <summary>Field number for the "mainItemPartsFound" field.</summary>
    public const int MainItemPartsFoundFieldNumber = 1;
    private static readonly pb::FieldCodec<long> _repeated_mainItemPartsFound_codec
        = pb::FieldCodec.ForInt64(8);
    private readonly pbc::RepeatedField<long> mainItemPartsFound_ = new pbc::RepeatedField<long>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<long> MainItemPartsFound {
      get { return mainItemPartsFound_; }
    }

    /// <summary>Field number for the "regularItemsTypesFound" field.</summary>
    public const int RegularItemsTypesFoundFieldNumber = 2;
    private static readonly pb::FieldCodec<long> _repeated_regularItemsTypesFound_codec
        = pb::FieldCodec.ForInt64(16);
    private readonly pbc::RepeatedField<long> regularItemsTypesFound_ = new pbc::RepeatedField<long>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<long> RegularItemsTypesFound {
      get { return regularItemsTypesFound_; }
    }

    /// <summary>Field number for the "rareItemTypesFound" field.</summary>
    public const int RareItemTypesFoundFieldNumber = 3;
    private static readonly pb::FieldCodec<long> _repeated_rareItemTypesFound_codec
        = pb::FieldCodec.ForInt64(24);
    private readonly pbc::RepeatedField<long> rareItemTypesFound_ = new pbc::RepeatedField<long>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<long> RareItemTypesFound {
      get { return rareItemTypesFound_; }
    }

    /// <summary>Field number for the "totalMainItemParts" field.</summary>
    public const int TotalMainItemPartsFieldNumber = 4;
    private readonly static long TotalMainItemPartsDefaultValue = 0L;

    private long totalMainItemParts_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long TotalMainItemParts {
      get { if ((_hasBits0 & 1) != 0) { return totalMainItemParts_; } else { return TotalMainItemPartsDefaultValue; } }
      set {
        _hasBits0 |= 1;
        totalMainItemParts_ = value;
      }
    }
    /// <summary>Gets whether the "totalMainItemParts" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasTotalMainItemParts {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "totalMainItemParts" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearTotalMainItemParts() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "totalRegularItemTypeCount" field.</summary>
    public const int TotalRegularItemTypeCountFieldNumber = 5;
    private readonly static long TotalRegularItemTypeCountDefaultValue = 0L;

    private long totalRegularItemTypeCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long TotalRegularItemTypeCount {
      get { if ((_hasBits0 & 2) != 0) { return totalRegularItemTypeCount_; } else { return TotalRegularItemTypeCountDefaultValue; } }
      set {
        _hasBits0 |= 2;
        totalRegularItemTypeCount_ = value;
      }
    }
    /// <summary>Gets whether the "totalRegularItemTypeCount" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasTotalRegularItemTypeCount {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "totalRegularItemTypeCount" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearTotalRegularItemTypeCount() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "totalRareItemTypeCount" field.</summary>
    public const int TotalRareItemTypeCountFieldNumber = 6;
    private readonly static long TotalRareItemTypeCountDefaultValue = 0L;

    private long totalRareItemTypeCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long TotalRareItemTypeCount {
      get { if ((_hasBits0 & 4) != 0) { return totalRareItemTypeCount_; } else { return TotalRareItemTypeCountDefaultValue; } }
      set {
        _hasBits0 |= 4;
        totalRareItemTypeCount_ = value;
      }
    }
    /// <summary>Gets whether the "totalRareItemTypeCount" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasTotalRareItemTypeCount {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "totalRareItemTypeCount" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearTotalRareItemTypeCount() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "itemTypesToFind" field.</summary>
    public const int ItemTypesToFindFieldNumber = 7;
    private static readonly pb::FieldCodec<long> _repeated_itemTypesToFind_codec
        = pb::FieldCodec.ForInt64(56);
    private readonly pbc::RepeatedField<long> itemTypesToFind_ = new pbc::RepeatedField<long>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<long> ItemTypesToFind {
      get { return itemTypesToFind_; }
    }

    /// <summary>Field number for the "mainItemType" field.</summary>
    public const int MainItemTypeFieldNumber = 8;
    private readonly static long MainItemTypeDefaultValue = 0L;

    private long mainItemType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long MainItemType {
      get { if ((_hasBits0 & 8) != 0) { return mainItemType_; } else { return MainItemTypeDefaultValue; } }
      set {
        _hasBits0 |= 8;
        mainItemType_ = value;
      }
    }
    /// <summary>Gets whether the "mainItemType" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasMainItemType {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "mainItemType" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearMainItemType() {
      _hasBits0 &= ~8;
    }

    /// <summary>Field number for the "regularItemTypesToFind" field.</summary>
    public const int RegularItemTypesToFindFieldNumber = 9;
    private static readonly pb::FieldCodec<long> _repeated_regularItemTypesToFind_codec
        = pb::FieldCodec.ForInt64(72);
    private readonly pbc::RepeatedField<long> regularItemTypesToFind_ = new pbc::RepeatedField<long>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<long> RegularItemTypesToFind {
      get { return regularItemTypesToFind_; }
    }

    /// <summary>Field number for the "rareItemTypesToFind" field.</summary>
    public const int RareItemTypesToFindFieldNumber = 10;
    private static readonly pb::FieldCodec<long> _repeated_rareItemTypesToFind_codec
        = pb::FieldCodec.ForInt64(80);
    private readonly pbc::RepeatedField<long> rareItemTypesToFind_ = new pbc::RepeatedField<long>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<long> RareItemTypesToFind {
      get { return rareItemTypesToFind_; }
    }

    /// <summary>Field number for the "tycoonOnly" field.</summary>
    public const int TycoonOnlyFieldNumber = 11;
    private readonly static bool TycoonOnlyDefaultValue = false;

    private bool tycoonOnly_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool TycoonOnly {
      get { if ((_hasBits0 & 16) != 0) { return tycoonOnly_; } else { return TycoonOnlyDefaultValue; } }
      set {
        _hasBits0 |= 16;
        tycoonOnly_ = value;
      }
    }
    /// <summary>Gets whether the "tycoonOnly" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasTycoonOnly {
      get { return (_hasBits0 & 16) != 0; }
    }
    /// <summary>Clears the value of the "tycoonOnly" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearTycoonOnly() {
      _hasBits0 &= ~16;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as TreasureHunt_AreaInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TreasureHunt_AreaInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!mainItemPartsFound_.Equals(other.mainItemPartsFound_)) return false;
      if(!regularItemsTypesFound_.Equals(other.regularItemsTypesFound_)) return false;
      if(!rareItemTypesFound_.Equals(other.rareItemTypesFound_)) return false;
      if (TotalMainItemParts != other.TotalMainItemParts) return false;
      if (TotalRegularItemTypeCount != other.TotalRegularItemTypeCount) return false;
      if (TotalRareItemTypeCount != other.TotalRareItemTypeCount) return false;
      if(!itemTypesToFind_.Equals(other.itemTypesToFind_)) return false;
      if (MainItemType != other.MainItemType) return false;
      if(!regularItemTypesToFind_.Equals(other.regularItemTypesToFind_)) return false;
      if(!rareItemTypesToFind_.Equals(other.rareItemTypesToFind_)) return false;
      if (TycoonOnly != other.TycoonOnly) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= mainItemPartsFound_.GetHashCode();
      hash ^= regularItemsTypesFound_.GetHashCode();
      hash ^= rareItemTypesFound_.GetHashCode();
      if (HasTotalMainItemParts) hash ^= TotalMainItemParts.GetHashCode();
      if (HasTotalRegularItemTypeCount) hash ^= TotalRegularItemTypeCount.GetHashCode();
      if (HasTotalRareItemTypeCount) hash ^= TotalRareItemTypeCount.GetHashCode();
      hash ^= itemTypesToFind_.GetHashCode();
      if (HasMainItemType) hash ^= MainItemType.GetHashCode();
      hash ^= regularItemTypesToFind_.GetHashCode();
      hash ^= rareItemTypesToFind_.GetHashCode();
      if (HasTycoonOnly) hash ^= TycoonOnly.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      mainItemPartsFound_.WriteTo(output, _repeated_mainItemPartsFound_codec);
      regularItemsTypesFound_.WriteTo(output, _repeated_regularItemsTypesFound_codec);
      rareItemTypesFound_.WriteTo(output, _repeated_rareItemTypesFound_codec);
      if (HasTotalMainItemParts) {
        output.WriteRawTag(32);
        output.WriteInt64(TotalMainItemParts);
      }
      if (HasTotalRegularItemTypeCount) {
        output.WriteRawTag(40);
        output.WriteInt64(TotalRegularItemTypeCount);
      }
      if (HasTotalRareItemTypeCount) {
        output.WriteRawTag(48);
        output.WriteInt64(TotalRareItemTypeCount);
      }
      itemTypesToFind_.WriteTo(output, _repeated_itemTypesToFind_codec);
      if (HasMainItemType) {
        output.WriteRawTag(64);
        output.WriteInt64(MainItemType);
      }
      regularItemTypesToFind_.WriteTo(output, _repeated_regularItemTypesToFind_codec);
      rareItemTypesToFind_.WriteTo(output, _repeated_rareItemTypesToFind_codec);
      if (HasTycoonOnly) {
        output.WriteRawTag(88);
        output.WriteBool(TycoonOnly);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      mainItemPartsFound_.WriteTo(ref output, _repeated_mainItemPartsFound_codec);
      regularItemsTypesFound_.WriteTo(ref output, _repeated_regularItemsTypesFound_codec);
      rareItemTypesFound_.WriteTo(ref output, _repeated_rareItemTypesFound_codec);
      if (HasTotalMainItemParts) {
        output.WriteRawTag(32);
        output.WriteInt64(TotalMainItemParts);
      }
      if (HasTotalRegularItemTypeCount) {
        output.WriteRawTag(40);
        output.WriteInt64(TotalRegularItemTypeCount);
      }
      if (HasTotalRareItemTypeCount) {
        output.WriteRawTag(48);
        output.WriteInt64(TotalRareItemTypeCount);
      }
      itemTypesToFind_.WriteTo(ref output, _repeated_itemTypesToFind_codec);
      if (HasMainItemType) {
        output.WriteRawTag(64);
        output.WriteInt64(MainItemType);
      }
      regularItemTypesToFind_.WriteTo(ref output, _repeated_regularItemTypesToFind_codec);
      rareItemTypesToFind_.WriteTo(ref output, _repeated_rareItemTypesToFind_codec);
      if (HasTycoonOnly) {
        output.WriteRawTag(88);
        output.WriteBool(TycoonOnly);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += mainItemPartsFound_.CalculateSize(_repeated_mainItemPartsFound_codec);
      size += regularItemsTypesFound_.CalculateSize(_repeated_regularItemsTypesFound_codec);
      size += rareItemTypesFound_.CalculateSize(_repeated_rareItemTypesFound_codec);
      if (HasTotalMainItemParts) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TotalMainItemParts);
      }
      if (HasTotalRegularItemTypeCount) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TotalRegularItemTypeCount);
      }
      if (HasTotalRareItemTypeCount) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TotalRareItemTypeCount);
      }
      size += itemTypesToFind_.CalculateSize(_repeated_itemTypesToFind_codec);
      if (HasMainItemType) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(MainItemType);
      }
      size += regularItemTypesToFind_.CalculateSize(_repeated_regularItemTypesToFind_codec);
      size += rareItemTypesToFind_.CalculateSize(_repeated_rareItemTypesToFind_codec);
      if (HasTycoonOnly) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TreasureHunt_AreaInfo other) {
      if (other == null) {
        return;
      }
      mainItemPartsFound_.Add(other.mainItemPartsFound_);
      regularItemsTypesFound_.Add(other.regularItemsTypesFound_);
      rareItemTypesFound_.Add(other.rareItemTypesFound_);
      if (other.HasTotalMainItemParts) {
        TotalMainItemParts = other.TotalMainItemParts;
      }
      if (other.HasTotalRegularItemTypeCount) {
        TotalRegularItemTypeCount = other.TotalRegularItemTypeCount;
      }
      if (other.HasTotalRareItemTypeCount) {
        TotalRareItemTypeCount = other.TotalRareItemTypeCount;
      }
      itemTypesToFind_.Add(other.itemTypesToFind_);
      if (other.HasMainItemType) {
        MainItemType = other.MainItemType;
      }
      regularItemTypesToFind_.Add(other.regularItemTypesToFind_);
      rareItemTypesToFind_.Add(other.rareItemTypesToFind_);
      if (other.HasTycoonOnly) {
        TycoonOnly = other.TycoonOnly;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10:
          case 8: {
            mainItemPartsFound_.AddEntriesFrom(input, _repeated_mainItemPartsFound_codec);
            break;
          }
          case 18:
          case 16: {
            regularItemsTypesFound_.AddEntriesFrom(input, _repeated_regularItemsTypesFound_codec);
            break;
          }
          case 26:
          case 24: {
            rareItemTypesFound_.AddEntriesFrom(input, _repeated_rareItemTypesFound_codec);
            break;
          }
          case 32: {
            TotalMainItemParts = input.ReadInt64();
            break;
          }
          case 40: {
            TotalRegularItemTypeCount = input.ReadInt64();
            break;
          }
          case 48: {
            TotalRareItemTypeCount = input.ReadInt64();
            break;
          }
          case 58:
          case 56: {
            itemTypesToFind_.AddEntriesFrom(input, _repeated_itemTypesToFind_codec);
            break;
          }
          case 64: {
            MainItemType = input.ReadInt64();
            break;
          }
          case 74:
          case 72: {
            regularItemTypesToFind_.AddEntriesFrom(input, _repeated_regularItemTypesToFind_codec);
            break;
          }
          case 82:
          case 80: {
            rareItemTypesToFind_.AddEntriesFrom(input, _repeated_rareItemTypesToFind_codec);
            break;
          }
          case 88: {
            TycoonOnly = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10:
          case 8: {
            mainItemPartsFound_.AddEntriesFrom(ref input, _repeated_mainItemPartsFound_codec);
            break;
          }
          case 18:
          case 16: {
            regularItemsTypesFound_.AddEntriesFrom(ref input, _repeated_regularItemsTypesFound_codec);
            break;
          }
          case 26:
          case 24: {
            rareItemTypesFound_.AddEntriesFrom(ref input, _repeated_rareItemTypesFound_codec);
            break;
          }
          case 32: {
            TotalMainItemParts = input.ReadInt64();
            break;
          }
          case 40: {
            TotalRegularItemTypeCount = input.ReadInt64();
            break;
          }
          case 48: {
            TotalRareItemTypeCount = input.ReadInt64();
            break;
          }
          case 58:
          case 56: {
            itemTypesToFind_.AddEntriesFrom(ref input, _repeated_itemTypesToFind_codec);
            break;
          }
          case 64: {
            MainItemType = input.ReadInt64();
            break;
          }
          case 74:
          case 72: {
            regularItemTypesToFind_.AddEntriesFrom(ref input, _repeated_regularItemTypesToFind_codec);
            break;
          }
          case 82:
          case 80: {
            rareItemTypesToFind_.AddEntriesFrom(ref input, _repeated_rareItemTypesToFind_codec);
            break;
          }
          case 88: {
            TycoonOnly = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
