// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: objects/turnbased_game.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WeevilWorldProtobuf.Objects {

  /// <summary>Holder for reflection information generated from objects/turnbased_game.proto</summary>
  public static partial class TurnbasedGameReflection {

    #region Descriptor
    /// <summary>File descriptor for objects/turnbased_game.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TurnbasedGameReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChxvYmplY3RzL3R1cm5iYXNlZF9nYW1lLnByb3RvEgdvYmplY3RzIksKElR1",
            "cm5iYXNlZEdhbWVUYWxseRILCgN3aW4YASABKAMSDAoEbG9zZRgCIAEoAxIM",
            "CgRkcmF3GAMgASgDEgwKBHF1aXQYBCABKANCT1ovNTVwaXhlbHMuY29tL3d3",
            "c2VydmVyL2ludGVybmFsL3Byb3RvYnVmL29iamVjdHOqAhtXZWV2aWxXb3Js",
            "ZFByb3RvYnVmLk9iamVjdHM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::WeevilWorldProtobuf.Objects.TurnbasedGameTally), global::WeevilWorldProtobuf.Objects.TurnbasedGameTally.Parser, new[]{ "Win", "Lose", "Draw", "Quit" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class TurnbasedGameTally : pb::IMessage<TurnbasedGameTally>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TurnbasedGameTally> _parser = new pb::MessageParser<TurnbasedGameTally>(() => new TurnbasedGameTally());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TurnbasedGameTally> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WeevilWorldProtobuf.Objects.TurnbasedGameReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TurnbasedGameTally() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TurnbasedGameTally(TurnbasedGameTally other) : this() {
      _hasBits0 = other._hasBits0;
      win_ = other.win_;
      lose_ = other.lose_;
      draw_ = other.draw_;
      quit_ = other.quit_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TurnbasedGameTally Clone() {
      return new TurnbasedGameTally(this);
    }

    /// <summary>Field number for the "win" field.</summary>
    public const int WinFieldNumber = 1;
    private readonly static long WinDefaultValue = 0L;

    private long win_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Win {
      get { if ((_hasBits0 & 1) != 0) { return win_; } else { return WinDefaultValue; } }
      set {
        _hasBits0 |= 1;
        win_ = value;
      }
    }
    /// <summary>Gets whether the "win" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasWin {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "win" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearWin() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "lose" field.</summary>
    public const int LoseFieldNumber = 2;
    private readonly static long LoseDefaultValue = 0L;

    private long lose_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Lose {
      get { if ((_hasBits0 & 2) != 0) { return lose_; } else { return LoseDefaultValue; } }
      set {
        _hasBits0 |= 2;
        lose_ = value;
      }
    }
    /// <summary>Gets whether the "lose" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasLose {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "lose" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearLose() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "draw" field.</summary>
    public const int DrawFieldNumber = 3;
    private readonly static long DrawDefaultValue = 0L;

    private long draw_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Draw {
      get { if ((_hasBits0 & 4) != 0) { return draw_; } else { return DrawDefaultValue; } }
      set {
        _hasBits0 |= 4;
        draw_ = value;
      }
    }
    /// <summary>Gets whether the "draw" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasDraw {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "draw" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearDraw() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "quit" field.</summary>
    public const int QuitFieldNumber = 4;
    private readonly static long QuitDefaultValue = 0L;

    private long quit_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Quit {
      get { if ((_hasBits0 & 8) != 0) { return quit_; } else { return QuitDefaultValue; } }
      set {
        _hasBits0 |= 8;
        quit_ = value;
      }
    }
    /// <summary>Gets whether the "quit" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasQuit {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "quit" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearQuit() {
      _hasBits0 &= ~8;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as TurnbasedGameTally);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TurnbasedGameTally other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Win != other.Win) return false;
      if (Lose != other.Lose) return false;
      if (Draw != other.Draw) return false;
      if (Quit != other.Quit) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasWin) hash ^= Win.GetHashCode();
      if (HasLose) hash ^= Lose.GetHashCode();
      if (HasDraw) hash ^= Draw.GetHashCode();
      if (HasQuit) hash ^= Quit.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasWin) {
        output.WriteRawTag(8);
        output.WriteInt64(Win);
      }
      if (HasLose) {
        output.WriteRawTag(16);
        output.WriteInt64(Lose);
      }
      if (HasDraw) {
        output.WriteRawTag(24);
        output.WriteInt64(Draw);
      }
      if (HasQuit) {
        output.WriteRawTag(32);
        output.WriteInt64(Quit);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasWin) {
        output.WriteRawTag(8);
        output.WriteInt64(Win);
      }
      if (HasLose) {
        output.WriteRawTag(16);
        output.WriteInt64(Lose);
      }
      if (HasDraw) {
        output.WriteRawTag(24);
        output.WriteInt64(Draw);
      }
      if (HasQuit) {
        output.WriteRawTag(32);
        output.WriteInt64(Quit);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasWin) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Win);
      }
      if (HasLose) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Lose);
      }
      if (HasDraw) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Draw);
      }
      if (HasQuit) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Quit);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TurnbasedGameTally other) {
      if (other == null) {
        return;
      }
      if (other.HasWin) {
        Win = other.Win;
      }
      if (other.HasLose) {
        Lose = other.Lose;
      }
      if (other.HasDraw) {
        Draw = other.Draw;
      }
      if (other.HasQuit) {
        Quit = other.Quit;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Win = input.ReadInt64();
            break;
          }
          case 16: {
            Lose = input.ReadInt64();
            break;
          }
          case 24: {
            Draw = input.ReadInt64();
            break;
          }
          case 32: {
            Quit = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Win = input.ReadInt64();
            break;
          }
          case 16: {
            Lose = input.ReadInt64();
            break;
          }
          case 24: {
            Draw = input.ReadInt64();
            break;
          }
          case 32: {
            Quit = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
